- transformation/common/src/main/java/org/jboss/mapper/camel/CamelBlueprintBuilder.java
- transformation/common/src/main/java/org/jboss/mapper/camel/CamelConfigBuilder.java
- transformation/common/src/main/java/org/jboss/mapper/camel/CamelEndpoint.java
- transformation/common/src/main/java/org/jboss/mapper/camel/CamelSpringBuilder.java
- transformation/common/src/test/java/org/jboss/mapper/camel/CamelConfigBuilderTest.java
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/META-INF/MANIFEST.MF
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/plugin.xml
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/wizards/NewTransformationWizard.java
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/extensions/DataTransformationPaletteEntry.java
This does not include the updates required to Fuse tooling commons to support serialization of camel context elements outside route definitions.  I will file a separate issue for that.
> issue #109 add support for data transformation palette extension

- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/TransformationEditor.java
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingDetailViewer.java
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingSummary.java
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingViewer.java
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/TransformationConfig.java
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/Util.java
This contains a temporary hack that ensures validation works correctly when setting or dropping fields in a mapping.
The hack is terribly inefficient, but will be removed once the backend is eventually updated to correct inconsistencies between the models within the config root models vs. those in the mappings.
> Fixes #252: Add validation for field and variable mappings

- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/ModelTabFolder.java
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/SourceTabFolder.java
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/TargetTabFolder.java
Also changed so that selecting an existing variable mapping selects the variables tab and applicable variable in the source tab folder.
> FUSETOOLS-1401: Mapped state of field in target model doesn't get updated after inclusion in expression mapping

- transformation/plugins/org.jboss.tools.fuse.transformation.editor/.classpath
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/META-INF/MANIFEST.MF
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/build.properties
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/pom.xml
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/ClasspathXMLResourceSelectionDialog.java
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/XMLPage.java
Also fixed an issue introduced by the jar refactoring in FUSETOOLS-1421 where we really need access to jaxb-impl as well as xjc. Otherwise we can't generate models successfully.
> FUSETOOLS-1453 - making XML picker a bit smarter

- pom.xml
characters
following https://issues.jboss.org/browse/FUSETOOLS-1647 I think that it would be a good idea
> Launch Integration tests in a workspace which path contains special

- core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/diagram/BasicNodeValidator.java
- core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/diagram/IFuseMarker.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelEditor.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/GoToMarkerForCamelEditor.java
- editor/tests/org.fusesource.ide.camel.editor.tests/src-test/java/org/fusesource/ide/camel/editor/GoToMarkerForCamelEditorTest.java
FUSETOOLS-1656)
It redirects to Source editor when there is a line number provided and
no corresponding element found.
> Select Diagram node when double-clicking on Marker in problem view (see

- core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/diagram/BasicNodeValidator.java
Nota: currently only a single warning validation exists, when ref and uri are specified. i'm not sure about the accuracy of this validation as the uri is set as required. Anyway, the mechanism will be set up
> Support info and warning validation (see FUSETOOLS-1657)

- editor/plugins/org.fusesource.ide.launcher.ui/src/org/fusesource/ide/launcher/ui/launch/ExecutePomActionSupport.java
name (see FUSETOOLS-1647)
It helps to support workspace containing @ and & characters in path.
> Use provided utility method to ensure having valid launch configuration

- core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/diagram/BasicNodeValidator.java
- core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/diagram/IFuseMarker.java
- core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/xml/XMLCamelRoutesValidator.java
- editor/plugins/org.fusesource.ide.camel.editor/META-INF/MANIFEST.MF
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelDesignEditor.java
- editor/plugins/org.fusesource.ide.project/META-INF/MANIFEST.MF
- editor/plugins/org.fusesource.ide.project/plugin.xml
- editor/plugins/org.fusesource.ide.project/src/org/fusesource/ide/project/decorator/CamelRouteProblemDecorator.java
- editor/plugins/org.fusesource.ide.project/src/org/fusesource/ide/project/providers/CamelFilesContentProvider.java
FUSETOOLS-1659)
I detected some refresh issue of the markers in Problem explorer view.
Some are related to what I have done and some others were already there (the ones on the xml file)
I can't figure out what is happening. I think it is worthy enough to provide it as is anyway. The user just need to call Refresh (F5) on the project when it occurs.
> Provide Validation decorator in project explorer view (see

- core/plugins/org.fusesource.ide.foundation.ui/META-INF/MANIFEST.MF
- core/plugins/org.fusesource.ide.foundation.ui/src/org/fusesource/ide/foundation/ui/tree/NodeSupport.java
- core/plugins/org.fusesource.ide.foundation.ui/src/org/fusesource/ide/foundation/ui/tree/RefreshNodeRunnable.java
- jmx/plugins/org.fusesource.ide.jmx.camel/src/org/fusesource/ide/jmx/camel/navigator/CamelContextNode.java
decorator is now correctly refreshed when using start/stop tracing on Context node AND on Route node
> FUSETOOLS-1427 - Refresh Camel Nodes in JMX View on start/stop tracing

- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelDesignEditor.java
On Windows, if an element is selected and an Help decorator drawn, the
go into will refresh everything and Graphiti will have disposed some
Fonts. So clear selection to avoid this issue.
> FUSETOOLS-1678 - Unselect container to avoid Graphic disposed

- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelGlobalConfigEditor.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/create/ext/CreateFigureFeature.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/utils/MavenUtils.java
- editor/tests/org.fusesource.ide.camel.editor.tests/src-test/java/org/fusesource/ide/camel/editor/utils/MavenUtilsTest.java
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/TransformationEditor.java
using m2e Maven dependencies on a pom provides support for Managed
Dependencies version
/!\ in case the project is not imported in the workspace, if the version comes from a parent pom, the current version will be added (but at least we won't have anymore a NPE and user really should to import its projects)
> FUSETOOLS-1562 - Use m2e Maven dependencies

- core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/ValidationFactory.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/provider/ToolBehaviourProvider.java
- editor/tests/org.fusesource.ide.camel.editor.tests/src-test/java/org/fusesource/ide/camel/editor/provider/ToolBehaviourProviderTest.java
provide a "multi validation decorator"
- Validation decorator are always shifted in order to never have
overlapping
- if several validation issues of a kind are reported, a single
decorator is added with a concatenated tooltip message
> FUSETOOLS-1658 - Avoid overlap for breakpoint/validation decorators and

- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelGlobalConfigEditor.java
It avoids having to switch between to reload the model before the
Properties view are available
Is it the right way to do?
I didn't found a buld for the endpoint. The only one available is in transformation and it adds the endpoint with an EIP "from" although when reloaded the model was "to"
But I am even  not sure of the from/to, maybe it should stay "endpoint" and I need to modify the AdvancedpropertiesFilter
> FUSETOOLS-1706 - Set underlying metamodel when creating global endpoint

- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/dialogs/GlobalConfigElementsSelectionDialog.java
worth testing on Linux in case events are not triggered in same order
> FUSETOOLS-1717 - Support double-click to go to next wizard

- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/commands/DiagramOperations.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/commands/ImportCamelContextElementsCommand.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/commands/LayoutCommand.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/add/AddFlowFeature.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/add/AddNodeFeature.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/create/CreateFlowFeature.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/CamelDiagramLoader.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/utils/NodeUtils.java
We are doing a batch import of every elements of the model. Layouting is
needed only at the end of this import.
> FUSETOOLS-1767 - Call layout only at the end of the import

- jmx/plugins/org.fusesource.ide.jmx.commons/.settings/org.moreunit.prefs
- jmx/plugins/org.fusesource.ide.jmx.commons/src/org/fusesource/ide/jmx/commons/backlogtracermessage/BacklogTracerEventMessage.java
- jmx/plugins/org.fusesource.ide.jmx.commons/src/org/fusesource/ide/jmx/commons/backlogtracermessage/DateAdapter.java
- jmx/tests/org.fusesource.ide.jmx.commons.tests/src/test/java/org/fusesource/ide/jmx/commons/backlogtracermessage/BacklogTracerEventMessageParserTest.java
The date format is hardcoded. It must corresponds to the hardcoded value in Camel core https://github.com/apache/camel/blob/camel-2.17.1/camel-core/src/main/java/org/apache/camel/api/management/mbean/BacklogTracerEventMessage.java#L28
What is the best to handle the correlation?
> FUSETOOLS-1827 - Support new Date format from JMX to display in Messages

- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/commands/ImportCamelContextElementsCommand.java
I suppose that this use case might happen when there is an invalid xml
file.
> FUSETOOLS-1920 - Avoid NPE when there is no model linked to Editor

- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/adopters/AbstractProjectTemplate.java
- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/adopters/configurators/MavenTemplateConfigurator.java
- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/FuseIntegrationProjectCreatorRunnable.java
classpath
- also wait for Refresh Build finished to avoid some "Resource out of
sync" even if no issue detected from that, except trace in log
- also provide the monitor and declare it as Done, the creator of the
monitor is reponsible for that.
> FUSETOOLS-1970 - Ensure a build has been done before searching in Java

- core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelFilesFinder.java
- core/plugins/org.fusesource.ide.camel.validation/plugin.xml
initialization error
- avoid to trigger XML Camel Route validation on all xml files
- avoid to check for content types when file is out of sync
> FUSETOOLS-1953 - Better filtering to avoid logged exception and

- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/FuseIntegrationProjectCreatorRunnable.java
InterruptedException
not a perfect solution, I can just hope that the Eclipse issue https://bugs.eclipse.org/bugs/show_bug.cgi?id=335251 won't be triggered too many triggered InteruptedException when importing a Camel project.
If it is the case, the user can still do alt+F5 after the import to workaround the issue.
previously, the camel facet were not imported something like 1 out 5 times on CI, so I will trigger the build 20 times to see if the workaround/fix is sustainable.
> FUSETOOLS-1991 - Wait only 30 times for Job in case of

- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelDesignEditor.java
disposed
I don't see easy and meaningful way to test it, there is no method to know if the listener are still registered or not.
> FUSETOOLS-1581 - Remove Breakpoint and Debug listeners when editor is

- servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/publish/jmx/KarafBundlesMBeanPublishBehaviour.java
- servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/publish/jmx/MavenPublishController.java
- servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/Karaf2xPublishController.java
- call mvn package before each full publication of a Module.
the downside of this approach is that it takes more time to do a full publish BUT it forces to have an up-to-date version when we call "full publish" I think that it is what user wants
note: We don't have test with a Fuse Runtime Server, currently only QE does that
> FUSETOOLS-1997 - Have deployment before build working

- jmx/plugins/org.fusesource.ide.jmx.camel/src/org/fusesource/ide/jmx/camel/navigator/CamelContextNode.java
- ensure hidden project is open
- ensure file is not out of sync (to avoid stacks in log from
Validation)
> FUSETOOLS-1970 - Improve robustness during investigation

- editor/plugins/org.fusesource.ide.launcher.ui/plugin.xml
- editor/plugins/org.fusesource.ide.launcher.ui/src/org/fusesource/ide/launcher/ui/propertytester/CamelLocalLaunchPropertyTester.java
- editor/tests/org.fusesource.ide.launcher.ui.tests/src/test/java/org/fusesource/ide/launcher/ui/propertytester/CamelLocalLaunchPropertyTesterTest.java
- fix regression introduced by commit
687e901ddfbf85a37470ed1c55283279bf9dd630 which is hiding Launch
shortcuts for local camel context in case of missing camel-maven-plugin
> FUSETOOLS-2019 - Ensure Launch shortcuts available on source editor

- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/adopters/configurators/MavenTemplateConfigurator.java
- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/META-INF/MANIFEST.MF
- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableCheckForBomVersionIT.java
- currently rely on the fact the UI will have restrained the list of
possible choice and that we have a 1-1 mapping between fuse bom version
and camel version
> FUSETOOLS-2071 - Set Fuse bom version when Target runtime selected

- servers/plugins/org.fusesource.ide.server.karaf.core/plugin.xml
- servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/Karaf2xPublishController.java
updating publishing to not do the maven build in the middle, while
adding the version to the deployed jar for more granularity
> FUSETOOLS-2018 - removing build path elements for Fuse 6.3 servers and

- core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/AbstractCamelModelElement.java
- core/tests/org.fusesource.ide.camel.model.service.core.tests/src/test/java/org/fusesource/ide/camel/model/service/core/model/AbstractCamelModelElementTest.java
there is another issue which is that the referenced endpoint is not resolved, but we will have the default icon instead of a NPE. Seems to be a first good step.
> FUSETOOLS-2060 - Always return non-null value for iconName

- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/l10n/Messages.java
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/l10n/messages.properties
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/ImportExportPackageUpdater.java
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/wizards/NewTransformationWizard.java
- transformation/tests/org.jboss.tools.fuse.transformation.editor.tests.integration/META-INF/MANIFEST.MF
- transformation/tests/org.jboss.tools.fuse.transformation.editor.tests.integration/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/ImportExportPackageUpdaterForManifestIT.java
- transformation/tests/org.jboss.tools.fuse.transformation.editor.tests.integration/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/ImportExportPackageUpdaterForPomIT.java
- transformation/tests/org.jboss.tools.fuse.transformation.editor.tests/src/test/java/org/jboss/tools/fuse/transformation/editor/internal/util/ImportExportPackageUpdaterTest.java
- in case of using a commited MANIFEST.MF: complete the export-package
list in the Manifest.mf file
- in case of using maven-bundle-plugin:
-- if no export package configured at all: do nothing
-- if some export package configured: complete the export-package list
in the pom.xml for the maven-bundle-plugin
> FUSETOOLS-2039 - Handle Export Package with Data Transformation

- core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelFilesFinder.java
- editor/plugins/org.fusesource.ide.launcher.ui/plugin.xml
Allows to have Bean code completion in xml
- Fix creation of Spring Templates when Spring IDE is installed
- Fix "Launch as camel context" shortcut when Spring IDE is installed
Can't write tests with current state as we don't have Spring IDE in TP
> FUSETOOLS-2117 - Improve compatibility with Spring IDE

- core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelFile.java
- core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/CamelIOHandlerIT.java
- core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/resources/jaas-blueprint.xml
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/CamelGlobalConfigEditor.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/GlobalConfigLabelProvider.java
- avoids to put ids for elements whcih don't support it
- avoids to show unsupported and unknown elements in Global
Configuration Editor that are part of other namespaces
Requires a validation from a Camel point of view:
- Am I missing some cases?
- Are we ok to hide elements in Configuration Editor that are not part of camel namespaces? (they can't be modified anyways)
> FUSETOOLS-2061 - Respect Namespace for Global Definitions

- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/extensions/DataMapperEndpointFigureFeature.java
to avoid having twice the same camel-dozer dependency
> FUSETOOLS-2016 - use super method directly

- core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/AbstractCamelModelElement.java
- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java
- the InterruptedException was triggered by IEventBroker.send called
- at creation of a project, if all ids are set, this shoudln't be
called, I improved the condition
- I added in check in test to ensure that the editor is nto dirty (to be
sure that no id is generated/modified during project creation which can
cause the IEventBroker.send to be called
> FUSETOOLS-1899 - Avoid InterruptedException on project creation

- core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/PropertiesUtils.java
- core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/util/PropertiesUtilsForPathParameterCheckIT.java
- core/tests/org.fusesource.ide.camel.model.service.core.tests/src/test/java/org/fusesource/ide/camel/model/service/core/util/PropertiesUtilsTest.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/AdvancedEndpointPropertiesSection.java
- it was occurring because the ModifyListener is calling an update on
the path parameters before the modelMap was completely initialized
- the solution consists to fall back to current model state if modelMap
is not initialized for the parameter required
> FUSETOOLS-2166 - Avoid losing path parameters when going back and forth

- editor/plugins/org.fusesource.ide.launcher.ui/META-INF/MANIFEST.MF
- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/CamelDebugTarget.java
- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/CamelStackFrame.java
- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/CamelThread.java
- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/variables/BaseCamelVariable.java
- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/variables/BaseWritableCamelIntegerVariable.java
- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/variables/BaseWritableCamelVariable.java
- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/variables/BaseWriteableCamelBooleanVariable.java
- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/variables/CamelBodyIncludeFilesVariable.java
- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/variables/CamelBodyIncludeStreamsVariable.java
- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/variables/CamelBodyMaxCharsVariable.java
- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/variables/CamelBodyVariable.java
- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/variables/CamelHeaderVariable.java
- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/variables/CamelLogLevelVariable.java
this is cleaner to use the Interface and it will be required if we want to provide a Jolokia Implementation for debugging. this will allow to debug camel routes deployed on IoT devices using Eclipse Kura for instance
> Clean code - use interface instead of Implementation

- editor/plugins/org.fusesource.ide.project/META-INF/MANIFEST.MF
it is required to have maven-bundle-plugin working correctly and be able
to deploy immediately after creation of a project to a server
> JBTIS-982 - Add back sonatype m2e plugin

- editor/plugins/org.fusesource.ide.project/lifecycle-mapping-metadata.xml
- editor/plugins/org.fusesource.ide.projecttemplates/lifecycle-mapping-metadata.xml
it avoids to have warnings in Eclipse
> Clean code - use xml Doctype declaration when no xsd/dtd available

- jmx/tests/org.fusesource.ide.jmx.commons.tests/META-INF/MANIFEST.MF
- pom.xml
- upgrade TP
- also downgrade commons.io dependency to 2.2 as 2.4 as been removed
> FUSETOOLS-2213 - Upgrade Target Platform to 4.4.1.CR1

- editor/plugins/org.fusesource.ide.projecttemplates/OSGI-INF/l10n/bundle.properties
- editor/plugins/org.fusesource.ide.projecttemplates/plugin.xml
- editor/plugins/org.fusesource.ide.projecttemplates/pom.xml
- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/simple/OSESpringBootXMLTemplate.java
- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/maven/CamelProjectConfigurator.java
- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/preferences/initializer/StagingRepositoriesPreferenceInitializer.java
- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/util/camel/CamelFacetVersionChangeDelegate.java
- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/util/maven/MavenUtils.java
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot/README.md
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot/configuration/settings.xml
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot/pom.xml
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot/src/main/fabric8/deployment.yml
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot/src/main/java/com/mycompany/Application.java
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot/src/main/java/com/mycompany/MyTransformer.java
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot/src/main/resources/application.properties
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot/src/main/resources/logback.xml
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot/src/main/resources/spring/camel-context.xml
- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForAMQIT.java
- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForCBRIT.java
- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForCXFCodeFirstIT.java
- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForOSESringBootIT.java
- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java
Provide a basic OpenShift SpringBoot template based on
fabric8-maven-plugin
- templates is based on fuse using fabric8 archetype catalog
2.2.0.fuse-000009
- removed the provided tests as they are not working: see
https://issues.jboss.org/browse/OSFUSE-484
- when new versions of FIS will be available, the template will need to
be updated
> FUSETOOLS-2151 - Provide basic OSE SpringBoot template

- core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/AbstractCamelModelElement.java
- core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/CamelIOHandlerIT.java
- core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/resources/withMarshalCsvHeaders.xml
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/FusePropertySection.java
first level
- current limitation is that elements can not contains a "," character
(still better than corrupting the data everytime before)
- in eips provided, no use case detected in which a "," can be used.
- UIs is providing a simple text comma separated
> FUSETOOLS-2216 - Basic support of list of elements for an eip not at

- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/adopters/configurators/DefaultTemplateConfigurator.java
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot/.settings/fusetooling/%%%PLACEHOLDER_PROJECTNAME%%% deploy on OpenShift.launch
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot/.settings/fusetooling/Launch locally %%%PLACEHOLDER_PROJECTNAME%%%.launch
- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForOSESringBootIT.java
- one for launching locally
- one for deploying on OpenShift with mandatory java system properties
pre-filled.
those Launch Configuratiosn are available when doing Run As -> Run configuration...
for the local one:
For the deployment on OpenShift using fabric8-maven-plugin:
- VM arguments are used because fabric8-maven-plugin is not supporting maven properties and environment variables seems to not working neither
> FUSETOOLS-2153 - Provide pre-configured Launch Configurations

- core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/diagram/BasicNodeValidator.java
when a resource is deleted, the Validation Job can still be running. In
this case we can just ignore it, markers are removed by Eclipse system.
> FUSETOOLS-2244 - Avoid exception when resource deleted

- Build.md
- pom.xml
- targetplatform/pom.xml
due to limitations, cannot use anymore a local Target Platform, so
changed to use the .target file provided by JBTIS Target Platform as a
temporary - I hope - workaround.
> FUSETOOLS-2240 - Upgrade to JBTIS TP 4.4.1.CR2

- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardRuntimeAndCamelPage.java
it was using the toString on the Selection instead of using the content
of the selection itself
providing the PR without test to check that i broke nothing else (and if someone want to write test)
I think that the "easiest" is to mock runtimes rturned by getServerRuntimes
> FUSETOOLS-2248 - Fix Camel version detection

- changeVersion.sh
- pom.xml
upgrading to corresponding JBTIS TP used, using SNAPSHOT because the non-snapshot artefact is not available on repositories
> Upgrade to 4.4.2.Final-SNAPSHOT

- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelDesignEditor.java
The workaround consists in resetting the selection to an empty one to
avoid graphic is disposed.
The current selection is more clearly lost now but it was -
unfortunately - already the case before
> FUSETOOLS-2246 - avoid graphic is disposed

- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/FusePropertySection.java
> FUSETOOLS-2218 - Double '&' to have it correctly displayed in native

- core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/io/CamelIOHandler.java
- core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/CamelIOHandlerForEmptyFileIT.java
it avoids stacks in log fo ran invalid camel file
> FUSETOOLS-2097 - return null if file is empty

- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/CamelDebugTarget.java
it avoids that the debugger is no more available when resume is called
and a stack to be written in logs
> FUSETOOLS-2287 - Call resume before Disabling debugger

- pom.xml
it introduces a change in qualifiers, it is now using the latest git
commit date instead of the time the build occured
> FUSETOOLS-2268 - Upgrade parent pom to 4.4.3.Final

- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelDesignEditor.java
To write some unit tests, it will require a too big refactor from my point of view.
We don't have yet integration tests about debugging, I created a task for that because I feel that it is a quite big task too. https://issues.jboss.org/browse/FUSETOOLS-2288
If you think that we really need to write those testsbefore merging this PR (and have ideas how to write them) please let me know
> FUSETOOLS-1938 - Highlight breakpoint only when the thread is suspended

- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/FusePropertySection.java
- fix desynchronization when switching between property sections
- slower navigation because the full section is recomputed
--> a UI test will be required for ensuring no regression
--> does the slowness introduced is acceptable?
if not what other solutions? Seems like we will need to recreate a notification system as EMF, or is there a simpler solution that I miss?
> FUSETOOLS-2292 - refresh property section when about to be shown

- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/FusePropertySection.java
because the aboutToBeShown is not called in that case
call the reinit only if objects are different (i removed this part unfrotunately in previous PR already merged)
> FUSETOOLS-2292 - reinit section on set input

- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/custom/DeleteAllEndpointBreakpointsFeature.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/custom/DisableCamelBreakpointFeature.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/custom/EditConditionalBreakpoint.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/custom/EnableCamelBreakpointFeature.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/custom/SetConditionalBreakpointFeature.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/custom/SetEndpointBreakpointFeature.java
- it should avoid NPE as the editor is retrieved from FeatureProvider
currently in use instead of the "potentially active one"
- factorize code to retrieve PictogramElement from Context of the
request
- replace spaces by tabs
> FUSETOOLS-2304 - More precise search of Camel Editor

- core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelFilesFinder.java
bad side is that it is using deprecated API but there is no replacement
for it and this is used in getContentDescription so no other choice
(except ignoring the exception but it is even uglier from my point of
view)
Other opinions?
> FUSETOOLS-2356 - Avoid stack in log for non local IFile

- editor/plugins/org.fusesource.ide.branding/OSGI-INF/l10n/bundle.properties
the provided archetype catalog has been used up until Fuse 6.2.1
version, it is now on normal redhat GA repository
> FUSETOOLS-2378 - Rename archetype catalog

- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/blank/blank-blueprint/pom.xml
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/amq/simple-fuse-activemq-blueprint/pom.xml
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/cbr/simple-fuse-cbr-blueprint/pom.xml
- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForCBRIT.java
2.18.1.redhat-000015
- exclude fileinstall as a workaround
- reactivate CBR test with 2.18 version
> FUSETOOLS-2388 - workaround to play blueprint test with Camel

- pom.xml
rebased version of https://github.com/jbosstools/jbosstools-fuse/pull/950 as the 4.4.3.CR1-SNAPSHOT seems to have vanished
> override the default surefire timeout

- core/plugins/org.fusesource.ide.imports/src/org/fusesource/ide/imports/sap/SapLibrariesFeatureArchive.java
Jaxb is supporting only String
need to be tested on a built environment (cannot go to the end with dev environment)
> FUSETOOLS-2464 - use String instead of Charset as Jaxb property

- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForCXFCodeFirstIT.java
as-is due to Fuse bom version mismatch
> Exclude Community version upper than 2.19 as the template is nto working

- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/util/maven/MavenUtils.java
there is a bug in io.fabric8 bom which leads to use always the latest
camel-maven-plugin instead of the expected version
> FUSETOOLS-2504 - don't use bom for camel plugins version management

- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/META-INF/MANIFEST.MF
> FUSETOOLS-2091 - Ensure arquilian xsd cache i availabel for test

- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/DetailsSection.java
computing
when changing languages or dataformat types, it might require a long
computation time due to download + compile time.
As this feature is making a bad experience to Users (UI freeze), we
choose to deactivate it.
> FUSETOOLS-2392 - Deactivating mouse wheel on combo requiring long

- servers/plugins/org.fusesource.ide.server.fuse.ui/plugin.xml
- servers/plugins/org.fusesource.ide.server.karaf.ui/plugin.xml
before:
after:
notice the icon at the top level tree item in Debug view
> FUSETOOLS-2527 - provide the icon for Karaf and Fuse launch config

- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/navigator/CamelCtxNavContentProvider.java
Display.getCurrent is returning null if it is not UI Thread
> FUSETOOLS-2530 - Ensure use UI thread when calling asynExec

- editor/plugins/org.fusesource.ide.project/src/org/fusesource/ide/project/providers/CamelVirtualFolder.java
- editor/tests/org.fusesource.ide.project.tests.integration/src/main/java/org/fusesource/ide/project/providers/CamelVirtualFolderIT.java
it avoids to scan all other projects, this will improve performance on
large workspaces
> FUSETOOLS-2472 - Return false when not interested in the resource

- servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/OSGiBundleStateController.java
- the returned value is currently never used so there was no functional
bugs but it would have been the case if tried to implement a feature
relying on it
> FUSETOOLS-2472 - return true when the connection is valid

- site/pom.xml
it avoids the Maven warning: [WARNING] The expression ${version} is
deprecated. Please use ${project.version} instead.
> FUSETOOLS-2546 - Use ${project.version} instead of ${version}

- core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/l10n/Messages.java
- core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/l10n/messages.properties
- core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/model/TextParameterValidator.java
- core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithEmptyAggregate.xml
- core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithEmptyFilter.xml
- core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithEmptyIdempotentConsumer.xml
- core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithEmptyIntercept.xml
- core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithEmptyInterceptFrom.xml
- core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithEmptyInterceptSendToEndpoint.xml
- core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithEmptyLoop.xml
- core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithEmptyMulticast.xml
- core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithEmptyOnCompletion.xml
- core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithEmptyPipeline.xml
- core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithEmptyPolicy.xml
- core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithEmptyResequence.xml
- core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithEmptySample.xml
- core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithEmptySplit.xml
- core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithEmptyThreads.xml
- core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithEmptyThrottle.xml
- core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithEmptyTransacted.xml
- core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithSameComponentIdAndComponentDefintionId.xml
- core/tests/org.fusesource.ide.camel.validation.tests.integration/src/org/fusesource/ide/camel/validation/xml/XMLCamelRoutesValidatorCheckIdIT.java
component definition id
in initial issue it was mentioned to add a warning also for cross-components because it is working but not a best practice.
I fear performance issue so maybe better to investigate more for the second part in another PR (perhaps issue too) to decide to decide to do it or not
> FUSETOOLS-2394 - report error validation for same component id and

- core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/internal/CamelModelServiceCoreActivator.java
- core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/internal/Trace.java
instances in a constructor
the parent should not be used static either so hard to do better than that but at least it removes the setting of static field in constructors (reported by Sonar as a code smell). I won't fight more on that as it is dead code and my personal point of view is that it should be completely removed.
> FUSETOOLS-2456 - apply Singleton pattern to avoid setting static

- servers/plugins/org.fusesource.ide.server.fuse.core/src/org/fusesource/ide/server/fuse/core/runtime/FuseESBRuntimeLocator.java
- servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/runtime/KarafRuntimeLocator.java
- servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/runtime/integration/KarafRuntimeDetector.java
- servers/tests/org.fusesource.ide.server.tests/META-INF/MANIFEST.MF
- servers/tests/org.fusesource.ide.server.tests/src/main/java/org/fusesource/ide/server/tests/locator/FuseESBRuntime6xLocatorIT.java
- servers/tests/org.fusesource.ide.server.tests/src/main/java/org/fusesource/ide/server/tests/locator/KarafRuntime2xLocatorIT.java
- servers/tests/org.fusesource.ide.server.tests/src/main/java/org/fusesource/ide/server/tests/locator/KarafRuntime3xLocatorIT.java
- servers/tests/org.fusesource.ide.server.tests/src/main/java/org/fusesource/ide/server/tests/locator/KarafRuntime4xLocatorIT.java
it helps to keep consistent naming, especially when using Dev Suite installer
> JBDS-4574 - Don't override runtime name with folder name

- pom.xml
it avoids to have too old version used which are not compatible with
Maven 3
> JBIDE-25139 - Specify Maven Sonar plugin version

- pom.xml
> FUSETOOLS-2580 - Remove sonar-maven-plugin management as it is

- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/adopters/AbstractProjectTemplate.java
- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/simple/AMQTemplate.java
- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/simple/OSESpringBootXMLTemplate.java
- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/internal/Messages.java
- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/l10n/messages.properties
- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/FuseIntegrationProjectWizard.java
- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardRuntimeAndCamelPage.java
- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardTemplatePage.java
- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/filter/CompatibleCamelVersionFilter.java
- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/filter/ExcludeEmptyCategoriesFilter.java
- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/model/TemplateItem.java
- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardTemplatePageIT.java
- editor/tests/org.fusesource.ide.projecttemplates.tests/src/test/java/org/fusesource/ide/projecttemplates/wizards/pages/filter/CompatibleCamelVersionFilterTest.java
- editor/tests/org.fusesource.ide.projecttemplates.tests/src/test/java/org/fusesource/ide/projecttemplates/wizards/pages/filter/ExcludeEmptyCategoriesFilterTest.java
@lhein @bfitzpat What do you think to this way to provide different templates depending on camel version chosen in previous page?
- I think it will be easy to extend to filter base don Runtime too after.
- I think that it will greatly help with the Fuse 7 stuff, we will be able to provide a new Template completely different
- it allows to filter out the OpenShift template for Camel version < .18 which are not working for sure.
> Fusetools 2195 select runtime camel version filter templates

- core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/jmx/camel/CamelContextMBean.java
- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/CamelDebugTarget.java
- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/JMXCamelConnectJob.java
- editor/tests/org.fusesource.ide.launcher.tests.integration/META-INF/MANIFEST.MF
- editor/tests/org.fusesource.ide.launcher.tests.integration/src/main/java/org/fusesource/ide/launcher/tests/integration/remote/debug/RemoteCamelDebugTester.java
- editor/tests/org.fusesource.ide.launcher.tests.integration/src/main/java/org/fusesource/ide/launcher/tests/integration/remote/debug/RemoteCamelLaunchConfigurationDelegateOverJolokiaIT.java
- jmx/plugins/org.fusesource.ide.jmx.camel/META-INF/MANIFEST.MF
Jolokia
the bug was in JBoss Tools, see
https://issues.jboss.org/browse/JBIDE-25428 but worth having a
non-regression tests for this important use case
WARNING: it requires https://github.com/jbosstools/jbosstools-server/pull/549 to be merged
> FUSETOOLS-2652 - Provide non-regression tests for route update through

- core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelMavenUtils.java
- core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/META-INF/MANIFEST.MF
- core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/util/CamelMavenUtilsTestIT.java
- not found a way to reproduce the reported error
- try to provide more robust way to retrieve the Maven project
- add test to cover more usecase
> FUSETOOLS-2514 - Avoid to have error when pom.xml is missing

- syndesis/tests/org.fusesource.ide.syndesis.extension.ui.tests.integration/build.properties
> FUSETOOLS-2715 - remove not existing folder from build.properties entry

- core/plugins/org.fusesource.ide.foundation.ui/src/org/fusesource/ide/foundation/ui/util/ControlDecorationHelper.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/FusePropertySection.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/creators/AbstractParameterPropertyUICreator.java
- syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/wizards/pages/SyndesisExtensionProjectWizardExtensionDetailsPage.java
- syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/wizards/pages/SyndesisExtensionProjectWizardVersionsPage.java
except on WizardLocation page as it is fully duplicated code that needs
to be refactored
the icon is slightly cropped on the left but it is the case everywhere in Eclipse, I don't know how to get rid of it.
> FUSETOOLS-2717 - Provide ControlDecoration information on focus

- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/actions/SwitchCamelVersionAction.java
- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/internal/Messages.java
- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/l10n/messages.properties
- editor/tests/org.fusesource.ide.projecttemplates.tests/src/test/java/org/fusesource/ide/projecttemplates/actions/SwitchCamelVersionActionTest.java
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/extensions/DataTransformationPaletteEntry.java
- transformation/tests/org.jboss.tools.fuse.transformation.editor.tests/META-INF/MANIFEST.MF
- transformation/tests/org.jboss.tools.fuse.transformation.editor.tests/src/test/java/org/jboss/tools/fuse/transformation/extensions/DataTransformationPaletteEntryTest.java
- removed the Data Transformation from palette
- provide information when switching Camel version using different incompatible Dozer version
to go further (another PR?)
- check that there is effectively Dozer used when switching Camel version
- check Camel version/dozer file when opening an already migrated Dozer file
> Fusetools 2668 disable transformation editor for camel2.20+

- syndesis/tests/org.fusesource.ide.syndesis.extension.ui.tests.integration/src/main/java/org/fusesource/ide/syndesis/extensions/tests/integration/wizards/SyndesisExtensionProjectCreatorRunnableForSimpleIT.java
> FUSETOOLS-2714 - removed unused rule attribute tmpFolder from test

- servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/util/KarafUtils.java
when adding functionality of Stripping Parameters in FUSETOOLS-2228 , it
removed the support of "null" symbolic name. Don't know how to reproduce
it and in which case it occurs exactly but at least we avoid NPE and
come back to previous behavior.
> FUSETOOLS-2558 - Avoid NPE

- syndesis/plugins/org.fusesource.ide.syndesis.extension.core/src/org/fusesource/ide/syndesis/extensions/core/util/SyndesisExtensionsUtil.java
- syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/wizards/pages/SyndesisExtensionProjectWizardVersionsPage.java
- syndesis/tests/org.fusesource.ide.syndesis.extension.core.tests/src/test/java/org/fusesource/ide/syndesis/extensions/core/model/SyndesisExtensionUtilVersionLoaderTest.java
- syndesis/tests/org.fusesource.ide.syndesis.extension.ui.tests.integration/src/main/java/org/fusesource/ide/syndesis/extensions/tests/integration/wizards/SyndesisExtensionProjectCreatorRunnableIT.java
> load versions for ignite extension wizard dynamically from file in this repo

- core/tests/org.fusesource.ide.camel.tests.util/src/org/fusesource/ide/camel/test/util/editor/AbstractCamelEditorIT.java
don't need to close all perspectives, just need to have the Fuse one
opened. On my machine, it saves 450ms per test, and it affects 99 tests.
It should save 50"
> Don't close all perspective to speed up test execution

- core/plugins/org.fusesource.ide.help/.project
API baseline is not used for Fuse Tooling project, remove the builder
from the only plugin that is invoking it.
> FUSETOOLS-2338 - Remove API baseline

- core/plugins/org.fusesource.ide.foundation.ui/src/org/fusesource/ide/foundation/ui/util/ControlDecorationHelper.java
- several of them are showing up only on focus anyway
- several of them are part of a different tab and so not displayed
immediately
- on my machine it helps to display ftp advanced tab from 4s to 500ms
without noticing any delay on display
> FUSETOOLS-2399 - Create Decoration asynchronously

- servers/plugins/org.fusesource.ide.server.fuse.core/plugin.xml
- servers/plugins/org.fusesource.ide.server.karaf.core/plugin.xml
- servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/Karaf2xPublishController.java
As bug has been fixed upstream
https://bugs.eclipse.org/bugs/show_bug.cgi?id=465141, the workaround can
be removed
https://github.com/jbosstools/jbosstools-fuse/commit/cc1b1e2137d327db4d0774345528e39e1bb46544
> FUSETOOLS-1317 - Publish module on start of Karaf/Fuse servers

- pom.xml
set Templates integration tests in a separated profile to allow to
launch in different jobs as they are failing a lot on CI currently 
> FUSETOOLS-2833 - create 2 profiles splitting tests

- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot-fuse7/.settings/fusetooling/Deploy %%%PLACEHOLDER_PROJECTNAME%%% on OpenShift.launch
change registry.access.redhat.com/jboss-fuse-7/fuse-java-openshift to registry.access.redhat.com/fuse7/fuse-java-openshift which will be the name for Fuse 7
/!\ /!\ it is not possible to test it before the GA! (not even internally) /!\ /!\
currently only tech previews are pushed with a different strange name.
It means that:
- before GA, users will need to modify the value but "ok, this is tech preview"
- after GA everything is fine!
the other solution would be to provide tech preview name, it would mean:
- before GA, it will work
- after GA, the wrong image will be used and so no assurance that it will work or not
> FUSETOOLS-2866 - Update image name from jboss-fuse-7 to fuse7

- core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/l10n/Messages.java
- core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/l10n/messages.properties
- core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/model/NumberValidator.java
- core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/CamelPlaceHolderUtil.java
- core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/Strings.java
- core/tests/org.fusesource.ide.camel.validation.tests.integration/src/org/fusesource/ide/camel/validation/model/NumberValidatorIT.java
- core/tests/org.fusesource.ide.foundation.core.test/src/test/java/org/fusesource/ide/foundation/core/util/CamelPlaceHolderUtilTest.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/creators/modifylisteners/number/AbstractNumberModifyListener.java
placeholders
not handling all kind of placeholders and the updated ones but at least
holding the default one with {{ and }}
> FUSETOOLS-2899 - avoid showing error for numeric values using default

- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardRuntimeAndCamelPage.java
> FUSETOOLS-2879 - filter runtime in "New Runtime" wizard

- core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/catalog/cache/CamelModel.java
- core/plugins/org.fusesource.ide.camel.model.service.impl/src/org/fusesource/ide/camel/model/service/internal/CamelModelPatcher.java
dataformat
different case, it is called zipFile in some places and zipfile in some
others.
> FUSETOOLS-2924 - workaround upstream inconsistency for zipFile

- pom.xml
https://issues.jboss.org/browse/FUSETOOLS-2967
- change the update site for OpenShift feature from snapshot to staging
> FUSETOOLS-2967 - Fix UI tests in PR job

- uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/SingleFuseProjectTest.java
https://issues.jboss.org/browse/FUSETOOLS-2969
- SingleFuseProjectTest does not try launch a project as Local Camel Context
> FUSETOOLS-2969 - Fix 'SingleFuseProjectTest'

- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardRuntimeAndCamelPage.java
instance
- now the data model of EnvironmentData is correctly updated
- the version is added to the list of proposed version until next open
of the wizard (i think that it makes sense as the version is an
"available" version as it was extracted from an existing Runtime
instance)
> FUSETOOLS-2955 - Fix camel version databinding when selecting a Runtime

- editor/plugins/org.fusesource.ide.wsdl2rest/pom.xml
note: some dependencies are missing from Fuse 7 repository so keep using
community one for these ones
> FUSETOOLS-2965 - use Fuse 7 version for wsdl2rest dependencies

- uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/ForgeOption.java
- uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/condition/ForgeConsoleHasText.java
- uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/ForgeConsoleView.java
- uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ForgeProjectsTest.java
https://issues.jboss.org/browse/FUSETOOLS-3007
(You can create a Fuse Integration Projects via JBoss Forge)
> FUSETOOLS-3007 - New UI test for Forge projects

- editor/plugins/org.fusesource.ide.wsdl2rest/META-INF/MANIFEST.MF
- servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/runtime/classpath/KarafProjectRuntimeClasspathProvider.java
- servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/runtime/integration/AbstractStacksDownloadRuntimesProvider.java
- servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/SourcePathComputerDelegate.java
- servers/plugins/org.fusesource.ide.server.karaf.ui/src/org/fusesource/ide/server/karaf/ui/SshConnector.java
- servers/plugins/org.fusesource.ide.server.karaf.ui/src/org/fusesource/ide/server/karaf/ui/launch/KarafLaunchConfigTabGroup.java
- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/TransformTestWizardPage.java
configuration limitation
the timestamp provider is configured to ignore pom.xml modifications but
last modification was affecting only pom.xml 
> FUSETOOLS-3063 - dummy modification to workaround timestamp provider

- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/run/launching/FuseMavenLaunchDelegate.java
which is breaking Camel Source Lookup
implies to be back to pre-Photon capabilities for source lookup
> FUSETOOLS-3058 - deactivate "advanced source lookup"

- core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/AbstractCamelModelElement.java
- core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/CamelIOHandlerIT.java
- core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/resources/withCDATA.xml
- does not support completely when there is a mix of CDATA and
non-CDATA. In this case it will put everything in CDATA in an equivalent
semantic way.
> FUSETOOLS-3084 - Support pure CDATA in attributes

- core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelComponentUtils.java
- core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/l10n/Messages.java
- core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/l10n/messages.properties
- core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/model/NumberValidator.java
- core/tests/org.fusesource.ide.camel.validation.tests.integration/src/org/fusesource/ide/camel/validation/model/NumberValidatorIT.java
- core/tests/org.fusesource.ide.camel.validation.tests/src/test/java/org/fusesource/ide/camel/validation/model/NumberValidatorTest.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/creators/advanced/NumberParameterPropertyUICreatorForAdvanced.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/creators/details/NumberParameterPropertyUICreatorForDetails.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/creators/modifylisteners/number/AbstractNumberModifyListener.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/creators/modifylisteners/number/NumberModifyListenerForAdvanced.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/creators/modifylisteners/number/NumberModifyListenerForDetails.java
for Duration, there is no information in catalog, it seems to be only
possible with Integer and Long type which are decimal so we are better
for Double and Float than before and same precision for
Long/Integer/Duration
> FUSETOOLS-3149 - fix wrong validation for Double and Float

- uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorRoutesTest.java
- uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorTest.java
- uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ComponentTest.java
- uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ProblemsViewTest.java
- uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ProjectLocalRunTest.java
fast and dirty hack to unblock release process due to an incompatibility
between RedDeer and used Eclipse version with Jboss Tools Target
Platform
> FUSETOOLS-3187 - ignore failing test

- core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/io/CamelIOHandler.java
with java 11, the methods previously used with transformers is
introducing extra-lines on each lines which is breaking the field
containing the CDATA.
note that the saveAsCamelModel seems to be used only in test for real.
Other places referenced:
- Datatransformation, it is used only when the class field saveModel is
set to true which is never the case currently.
- CamelEditorPersistencyDiagram: currently not used, the saved is
intercepted at multieditor level, synchronizing the model with the
source tab and then saving from source tab.
> FUSETOOLS-3190 - use CamelFile method to have xml to save

- editor/plugins/org.fusesource.ide.project/src/org/fusesource/ide/project/CamelNatureTester.java
- editor/tests/org.fusesource.ide.project.tests.integration/META-INF/MANIFEST.MF
- editor/tests/org.fusesource.ide.project.tests.integration/src/main/java/org/fusesource/ide/project/CamelNatureTesterIT.java
- editor/tests/org.fusesource.ide.project.tests.integration/src/main/resources/fileWithSeveralContext.xml
xml files
The CamelVirtualFolder is already provisioning a listening mechanism
> FUSETOOLS-3186 - Use a cache for detecting if Camel project has Camel

- servers/plugins/org.fusesource.ide.server.fuse.core/src/org/fusesource/ide/server/fuse/core/server/subsystems/Fuse6xStartupLaunchConfigurator.java
- servers/plugins/org.fusesource.ide.server.karaf.core/META-INF/MANIFEST.MF
- servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/BaseKarafStartupLaunchConfigurator.java
- servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/Karaf2xStartupLaunchConfigurator.java
- servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/Karaf3xStartupLaunchConfigurator.java
- servers/tests/org.fusesource.ide.server.fuse.core.tests/src/test/java/org/fusesource/ide/server/fuse/core/server/subsystems/Fuse6xStartupLaunchConfiguratorTest.java
- servers/tests/org.fusesource.ide.server.fuse.core.tests/src/test/java/org/fusesource/ide/server/fuse/core/server/subsystems/Fuse7xStartupLaunchConfiguratorTest.java
- servers/tests/org.fusesource.ide.server.karaf.core.tests/src/test/java/org/fusesource/ide/server/karaf/core/server/subsystems/Karaf2xStartupLaunchConfiguratorTest.java
- servers/tests/org.fusesource.ide.server.karaf.core.tests/src/test/java/org/fusesource/ide/server/karaf/core/server/subsystems/Karaf3xStartupLaunchConfiguratorTest.java
- servers/tests/org.fusesource.ide.server.karaf.core.tests/src/test/java/org/fusesource/ide/server/karaf/core/server/subsystems/Karaf4xStartupLaunchConfiguratorTest.java
> FUSETOOLS-3218 - Not set unsupported Java 9+ VM argument when vm is 9+

- syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/maven/SyndesisExtensionProjectConfigurator.java
it can cause important delay if the Maven project has not been
initialized yet.
> FUSETOOLS-3186 - Avoid accessing classpath if nature already configured

- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/RestConfigEditor.java
the trick is to avoid to reset value from model to SWT Widget when it is
already the same. this problem is coming by the usage of Listeners
instead of Databinding. It would be better to use Databinding but
requires an important rewrite that we don't have time to do given
current priorities.
> FUSETOOLS-3254 - avoid setting back the cursor to beginning when typing

- editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/globalconfiguration/dataformat/wizards/NewDataFormatWizardIT.java
not found a way to have tests playing faster in a reliable way fo rnow
so reactivating only a subpart which is covering some specific cases and
the generic one. it won't detect if a dataformat from the catalog is
added with wrong values but this part should be handled by Camel itself
anyway. Also don't detect in case of specific case, this part stays a
problem onb our side.
> FUSETOOLS-3248 - reactivate a subpart of NewDataFormatWizardIT tests

- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/blank/blank-blueprint-fuse7/pom.xml
the internal mechanism in Fuse Tooling is supporting only "old" bom
style for 7.0.x. it started to support "new" bom style from 7.1 only.
> FUSETOOLS-3291 - Fix 7.0.x empty blueprint template

- syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/lifecycle-mapping-metadata.xml
extension-maven-plugin
it was available in older versions.
> FUSETOOLS-3291 - workaround missing m2e support for Syndesis

- sonar-project.properties
Since we are one of the early adopters of SonarCloud, our project still
belongs to the "Attic" organization - which was originally the only
organization on SonarCloud when the service started. Because of this,
until now, we did not have to specify the "sonar.organization" property
on our project since it was defaulting to the "Attic" org. For
consistency reasons, SonarSource are going to make this property
mandatory, which means that we have to set it to "default".
> FUSETOOLS2-49 - Add sonar.organization to default

- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/cbr/simple-fuse-cbr-java-fuse6/src/test/java/com/mycompany/camel/RouteXmlTest.java
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/cbr/simple-fuse-cbr-java-fuse7.1/src/test/java/com/mycompany/camel/RouteXmlTest.java
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/cbr/simple-fuse-cbr-java-fuse7/src/test/java/com/mycompany/camel/RouteXmlTest.java
> FUSETOOLS-3332 - remove unused import package in test class

- syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/wizards/pages/SyndesisExtensionProjectWizardExtensionDetailsPage.java
- syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/wizards/validation/SyndesisExtensionIdValidator.java
- syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/wizards/validation/SyndesisExtensionNameValidator.java
- syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/wizards/validation/SyndesisExtensionVersionValidator.java
new version of Target Platform doesn't allow anymore to use
UpdateValueStrategy.create(Converter) with a null value.
also specify generic types for better readability
blind push awaiting local target Platform build but at least it will start build of PRs in case it is enough
> FUSETOOLS-3333 - avoid NPE with UpdatevalueStrategy

- uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/utils/ProjectFactory.java
> FUSETOOLS-3320: Fix regex inside UI Tests to avoid failures on JDK11

- editor/plugins/org.fusesource.ide.wsdl2rest.ui/.classpath
- editor/plugins/org.fusesource.ide.wsdl2rest.ui/pom.xml
note versiosn of other dependencies can be found in this pom https://maven.repository.redhat.com/ga/org/jboss/fuse/wsdl2rest/wsdl2rest/0.8.0.fuse-760026-redhat-00001/wsdl2rest-0.8.0.fuse-760026-redhat-00001.pom
> FUSETOOLS-3327 - upgrade internal wsdl2rest version

- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/provider/ActiveMQPaletteEntry.java
- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/provider/ActiveMQPaletteEntryDependenciesManager.java
- editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/provider/ToolBehaviourProviderIT.java
- editor/tests/org.fusesource.ide.camel.editor.tests/src/test/java/org/fusesource/ide/camel/editor/provider/ActiveMQPaletteEntryTest.java
for Camel 2.x and SrpingBoot, there is no specific -starter artifact for
ActiveMQ. It has been provided for Camel 3.x only. As Eclipse Fuse
Tooling is currently not supporting Camel 3.x, the fix consists in
providing always the non-specific to springboot artifact.
> FUSETOOLS-3340 - fix activeMQ dependency for SpringBoot

- editor/plugins/org.fusesource.ide.wsdl2rest.ui/pom.xml
it worked locally and few times on Ci but it was by "chance". The
problem was coming from the repository itself. it was an intermittent
problem, depending on which real server the load-balancer was
redirecting. Issue is now fixed on server side.
> FUSETOOLS-3327 - remove repository exclusion which is not working

- core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/xml/namespace/FindNamespaceHandlerSupport.java
Platform
methods has been moved. See
eclipse/eclipse.platform.runtime@190d65c
.
the bad news is that it seems that we still need to use internal API.
using SaxParserFactory.newInstance() directly is failing several tests
tried to remove (close to) duplicated code with upstream but then it
wasn't working, not found the difference.
> FUSETOOLS-3318 - avoid compilation failure after upgrade of target

- core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtils.java
- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForAMQIT.java
- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForCBRIT.java
- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForCXFCodeFirstIT.java
- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForEAPSpringIT.java
- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForOSESringBootIT.java
- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForSimpleIT.java
- Fuse runtime is not providing anymore valid artifacts for that and
doesn't want to set it back.
- this is just removal of the test, the problem still exists for
end-users. A cleaner way would be to remove mechanic to look to online
versions, which would remove a great feature for testing against
unreleased version.
> ENTESB-14075 - stop testing templates with latest version

- core/features/org.fusesource.ide.core.feature/feature.xml
was referencing the wrong plugin id
> FUSETOOLS-3368 - fix feature

- editor/tests/org.fusesource.ide.branding.tests.integration/src/main/java/org/fusesource/ide/branding/tests/integration/wizards/AbstractNewCamelTestWizardIT.java
- editor/tests/org.fusesource.ide.branding.tests.integration/src/main/java/org/fusesource/ide/branding/tests/integration/wizards/NewCamelTestWizardWithCamelContextIT.java
- editor/tests/org.fusesource.ide.branding.tests.integration/src/main/java/org/fusesource/ide/branding/tests/integration/wizards/NewCamelTestWizardWithRoutesIT.java
- had to split the test to have 2 differents projects (FuseProject rule)
used
- added a small additional check on the content of the file
- added to close the WizardDialog at the end of the test to have cleaner
test
The Java editor doesn't seem to be opened in the test. Not sure why.
> Avoid empty system editor to open in tests

- core/plugins/org.fusesource.ide.camel.model.service.impl/.classpath
- core/plugins/org.fusesource.ide.camel.model.service.impl/META-INF/MANIFEST.MF
- core/plugins/org.fusesource.ide.camel.model.service.impl/build.properties
- core/plugins/org.fusesource.ide.camel.model.service.impl/pom.xml
the groovy lib doesn't match the camel version but this version has been
provided on Camel 2.25.x branch and it is working well so good chance
that it is not causing any problems.
JRE 15 is now shipped by default in Eclipse
> FUSETOOLS-3394 - upgrade grrovy lib to support JDK 14+

- core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/FuseProject.java
- editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/provider/ToolBehaviourProviderIT.java
- transformation/tests/org.jboss.tools.fuse.transformation.editor.tests.integration/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/ImportExportPackageUpdaterForPomIT.java
It allows to ensure unique names and avoid tests affecting each others.
> Use classname.methodName as project name if not specified

- uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ProblemsViewTest.java
- uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/utils/FuseToolingProblems.java
given that the computation of problems is done asynchronously through
Eclipse Jobs, it can be the cause of detected flakiness.
> FUSETOOLS2-977 - use conditional wait for checking Problems view

- core/tests/org.fusesource.ide.camel.tests.util/src/org/fusesource/ide/camel/tests/util/JDKInstaller.java
- editor/plugins/org.fusesource.ide.camel.editor/META-INF/MANIFEST.MF
- editor/plugins/org.fusesource.ide.launcher.ui/OSGI-INF/l10n/bundle.properties
- editor/plugins/org.fusesource.ide.launcher/META-INF/MANIFEST.MF
- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/CamelDebugFacade.java
- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/EventDispatchJob.java
- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/JMXCamelConnectJob.java
- editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/run/launching/FuseMavenLaunchDelegate.java
- editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java
requires https://github.com/jbosstools/jbosstools-fuse/pull/1639
(and https://github.com/jbosstools/jbosstools-base/pull/684 )
tested:
- local debug with Fuse 7.7 and Fuse 7.8 using "Debug as..." -> Local Camel Context --> working
- using local Jolokia connection with Fuse 7.8 --> working
- Camel on Fuse Karaf -> working
- automated test checking remote debug still working with old Camel versions already available
started to test:
- debug when deployed on OpenShift (using remote secured Jolokia). hit several known issues in Jboss Tools (reported 2 or 3 years ago)
not tested:
- Camel on EAP but similar code than for Fuse on Karaf
> Fusetools 3393 use local vm debug

- core/plugins/org.fusesource.ide.preferences/src/org/fusesource/ide/preferences/initializer/PreferencesInitializer.java
the syncExec was introduced here https://github.com/jbosstools/jbosstools-fuse/commit/a8b68f44442082ad2a07fa12b1049b3d2b2aa9fe#r46963310
the preference value is used fo rinstance when starting a route. Connecting through JMX Navigator, select a setBody, In properties view, select processors
to avoid this kind of stacks:
```
!ENTRY org.eclipse.ui 4 4 2021-02-09 04:01:15.611
!MESSAGE To avoid deadlock while executing Display.syncExec() with argument: org.fusesource.ide.preferences.initializer.PreferencesInitializer$$Lambda$714/0x0000000100d12040@4eba3b82, thread Worker-3: Synchronizing projects will interrupt UI thread.
!SUBENTRY 1 org.eclipse.ui 4 4 2021-02-09 04:01:15.611
!MESSAGE Worker-3: Synchronizing projects thread is an instance of Worker or owns an ILock
!STACK 0 …
```
> FUSETOOLS2-978 - remove syncExec block to avoid potential jobs deadlock

- uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DefaultTest.java
Given that DefaultTest.defaultSetup() is deletign workspace log, copying
it in case of test failure with anothe rname to have it available for
investigation
> FUSETOOLS2-980 - backup workspace log for UI test failure

- editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/provider/ToolBehaviourProviderIT.java
in practice, the editor is closed automatically but it is done in an
asynchronous way. In this test, it is complicated to wait for it and it
is not the purpose of this test. Consequently, a simple workaround is to
close the editor that the test has opened.
> FUSETOOLS-3416 - close editor to avoid stacktrace in log

- transformation/tests/org.jboss.tools.fuse.transformation.editor.tests.integration/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/ImportExportPackageUpdaterForManifestIT.java
to ensure that they are not affecting each other and it is not the cause
of potential flaky test
> FUSETOOLS2-396 - use different name for each test

- uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/projectexplorer/CamelProject.java
it sounds like the PSI Jenkins CI is slower and requires more time. it
seems that no mirror are configured for the projects on this CI.
> FUSETOOLS2-980 - increase timeout for project run

- pom.xml
it allows to not have to provide specific parameters on new PSI Jenkins
another possibility is to use an environment variable to activate profiles. it might be useful for PR jobs but maybe better to wait to be sure that it is required before using environment variables
> FUSETOOLS-3441 - launch only non-templates integration test by default

- pom.xml
tycho-source-plugin
as recommended after migrated to Tycho 2.2:
[WARNING] Mojo tycho-source-feature-plugin:source-feature is replaced by
the tycho-source-plugin:feature-source which offers equivalent and even
enhanced functionality
currently failing with:
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.fusesource.ide.updatesite raw:11.10.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):11.10.0-SNAPSHOT
[ERROR]   Missing requirement: org.fusesource.ide.updatesite raw:11.10.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):11.10.0-SNAPSHOT requires 'org.eclipse.equinox.p2.iu; org.fusesource.ide.camel.editor.feature.source.feature.group 0.0.0' but it could not be found
[ERROR] 
```
> FUSETOOLS-3442 - Migrate from tycho-source-feature-plugin to

- transformation/tests/org.jboss.tools.fuse.transformation.core.tests.integration/META-INF/MANIFEST.MF
since work on java 11 compatibility, the jaxb dependency is provided by
org.jboss.tools.common.jaxb
cc @sbouchet
> JBIDE-27598 - remove locus jaxb-xjc dependency

- editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/util/BasicProjectCreatorRunnable.java
an invalid META-INF/MANIFEST.MF is generated by jst.utility facet. A
workaround was previously provided in Fuse Tooling code to delete the
invalid generated META-INF folder. Starting with Eclipse 2021-03, the
default folder to generated this file has been moved from src to
src/main/java. So added this folder to be deleted to have it working
both in previous version of Eclipse and newer version.
it was detected by test
org.fusesource.ide.projecttemplates.tests.integration.wizards.FuseIntegrationProjectCreatorRunnableForOSESringBootIT.additionalChecks(IProject)
it is fixing regression after Target platform upgrade to Eclipse 2021-03
> FUSETOOLS-3461 - delete invalid MANIFEST.MF on new places

- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot-fuse7.9/pom.xml
given that anonymous access seems to have been moved from
registry.access.redhat.com to registry.redhat.io
> FUSETOOLS-3504 - use registry.redhat.io for Fuse 7.9

- pom.xml
Tycho 2.5.0 is [no more using pack200](https://www.eclipse.org/lists/cross-project-issues-dev/msg18273.html).
Pack200 was generating p2 metadata for source features (for its own internal need)
p2 metadata are required to build update site for some features sources (in our case _org.fusesource.ide.core.feature.source.feature.group_ even if I do not know why exactly)
To still generate these p2 metadata, adding the goal feature-p2-metadata to tycho-p2-plugin.
This metadata must be generated AFTER the source plugin is generated by the tycho-source-plugin. To achieve that, placing the goal of tycho-p2-plugin to the phase after, which is the verify phase.
> FUSETOOLS-3554 - Fix build with Tycho 2.5.0

- servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/BaseKarafStartupLaunchConfigurator.java
- servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/Karaf4xStartupLaunchConfigurator.java
the layout of jar folders has been slightly modified. 2 new folders
available endorsed and jdk9plus.
> FUSETOOLS-3567 - Support Fuse 7.10 with java 11

- core/tests/org.fusesource.ide.camel.validation.tests/META-INF/MANIFEST.MF
to the new version available in Target Platform. Old one (2.x) has been
removed
it will allow to fix the master branch
> FUSETOOLS-3596 - Upgrade AssertJ to 3.x

- editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/provider/ToolBehaviourProvider.java
- uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/component/Kafka.java
the component is nowadays used a lot.
not adding a specific icon as it requires in theory to go through
marketing and legal. it is not worthy enough compared to Eclipse Desktop
tooling priority
> FUSETOOLS-3590 - add kafka to palette by default

- transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/TransformationEditor.java
automatically is disabled
- "build automatically is disabled" might be the default with Eclipse
2022-03
- calling an incremental build on the project before we need to access
the generated java classes. As it is incremental, it will take no time
anyway if users have automatic build activated. For the others, it will
take some time but at least it will work.
- spotted that monitors are not correctly defined but do not want to
touch too many things in this part of the code which is very old and
which concerns Data Transformation which is no more recommended for a
long time.
> FUSETOOLS2-3637 - fix Data Transformation Editor opening when build

- editor/tests/org.fusesource.ide.launcher.tests/src/test/java/org/fusesource/ide/launcher/debug/model/CamelDebugTargetTest.java
not detected impact when testing manually. It sounds like a regression upstream. Deactivating at least for now so that it unblocks build
> FUSETOOLS-3670 - deactivate failing test with new Target platform

- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/blank/blank-blueprint-fuse7.10.1/pom.xml
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/blank/blank-java-fuse7.10.1/pom.xml
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/blank/blank-spring-fuse7.10.1/pom.xml
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/cxf-code-first/medium-fuse-cxf-code-first-java-fuse7.10.1/pom.xml
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/cxf-code-first/medium-fuse-cxf-code-first-spring-fuse7.10.1/pom.xml
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/cxf-contract-first/medium-fuse-cxf-contract-first-blueprint/pom.xml
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/cxf-contract-first/medium-fuse-cxf-contract-first-java/pom.xml
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/cxf-contract-first/medium-fuse-cxf-contract-first-spring/pom.xml
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/cbr/simple-fuse-cbr-blueprint-fuse7.10.1/pom.xml
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/cbr/simple-fuse-cbr-java-fuse7.10.1/pom.xml
- editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/cbr/simple-fuse-cbr-spring-fuse7.10.1/pom.xml
to workaround regression in Eclipse m2e connector. The version used is then not a strictly match with what is supported at runtime but it shouldn't cause a problem.
Workarounded only for latest versions
> FUSETOOLS-3665 - use newer maven-bundle-plugin

- pom.xml
which is required as runtime
it avoids this kind of error in log:
```
Caused by: java.io.IOException: Error while instrumenting org/fusesource/ide/launcher/debug/model/CamelDebugFacade$MockitoMock$FbAv5SJE$auxiliary$hqoeDniq.
at org.jacoco.agent.rt.internal_1f1cc91.core.instr.Instrumenter.instrumentError(Instrumenter.java:170)
at org.jacoco.agent.rt.internal_1f1cc91.core.instr.Instrumenter.instrument(Instrumenter.java:120)
at org.jacoco.agent.rt.internal_1f1cc91.CoverageTransformer.transform(CoverageTransformer.java:91)
... 57 more
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
at org.jacoco.agent.rt.internal_1f1cc91.asm.ClassReader.<init>(ClassReader.java:184)
at org.jacoco.agent.rt.internal_1f1cc91.asm.ClassReader.<init>(ClassReader.java:166)
at …
```
> Upgrade jacoco to support java 17
