jbosstools/jbosstools-fuse

transformation/plugins/org.jboss.tools.fuse.transformation.editor/.classpath
transformation/plugins/org.jboss.tools.fuse.transformation.editor/build.properties
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/TransformationEditor.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingDetailViewer.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingSummary.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingViewer.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingsViewer.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/ModelTabFolder.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/ModelViewer.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/PotentialDropTarget.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/Util.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/JavaPage.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/OtherPage.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/XMLPage.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/wizards/NewTransformationWizard.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/extensions/DataTransformationPaletteEntry.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/extensions/TransformationDblClickHandler.java

Also introduces highlighting of potential DnD drop targets

Fixes #181: Transformation editor's mapping summary list is incorrectly sized when empty

---

transformation/common/src/main/java/org/jboss/mapper/TransformType.java
transformation/common/src/main/java/org/jboss/mapper/camel/CamelConfigBuilder.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/ModelType.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/OtherPage.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/wizards/NewTransformationWizard.java

I added a commit on top of Brian's PR to fix a couple other issues I found while testing.

Issue #190 NPE in OtherPage of New Transformation Wizard

---

transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingDetailViewer.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingSummary.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingViewer.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingsViewer.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/OtherPage.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/wizards/NewTransformationWizard.java

and hanging when a drag is attempted after deleting a mapping

Fixes UI not re-laying out consistently after deleting a mapping

---

core/plugins/org.fusesource.ide.imports/META-INF/MANIFEST.MF
core/plugins/org.fusesource.ide.imports/src/org/fusesource/ide/imports/sap/ImportUtils.java
core/plugins/org.fusesource.ide.imports/src/org/fusesource/ide/imports/sap/Messages.java
core/plugins/org.fusesource.ide.imports/src/org/fusesource/ide/imports/sap/SapToolSuiteInstaller.java
core/plugins/org.fusesource.ide.imports/src/org/fusesource/ide/imports/sap/l10n/messages.properties

location identified by ‘jboss.discovery.site.integration-stack-extras.url’ property.

[FUSETOOLS-1258] Updated install wizard to use repo

---

transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/TransformationEditor.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingDetailViewer.java

Also fixes #233: Data Transformation: Missing Collapse tooltip

Fixes #200: List of expression languages should be editable drop-down.

---

transformation/common/src/main/java/org/jboss/tools/fuse/transformation/model/xml/XmlModelGenerator.java
transformation/common/src/test/java/org/jboss/tools/fuse/transformation/model/xml/XmlModelGeneratorTest.java
transformation/common/src/test/resources/org/jboss/tools/fuse/transformation/model/xml/multi-element.xsd

Convenience methods that Brian needed to implement #201

laying groundwork in common for issue #201

---

transformation/common/src/main/java/org/jboss/tools/fuse/transformation/dozer/DozerMapperConfiguration.java
transformation/common/src/main/java/org/jboss/tools/fuse/transformation/model/Model.java
transformation/common/src/test/java/example/ListsAndNestedTypes.java
transformation/common/src/test/java/org/jboss/tools/fuse/transformation/dozer/DozerMapperConfigurationTest.java
transformation/common/src/test/resources/org/jboss/tools/fuse/transformation/dozer/parentsAndLists.xml
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingDetailViewer.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/TransformationConfig.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/Util.java

issue #278 Fix parent lineage for existing transformation files

---

transformation/common/src/main/java/org/jboss/tools/fuse/transformation/model/xml/XmlModelGenerator.java
transformation/common/src/test/java/org/jboss/tools/fuse/transformation/model/xml/XmlModelGeneratorTest.java
transformation/common/src/test/resources/org/jboss/tools/fuse/transformation/model/xml/Application.xsd

issue #305 Pick up @XmlElementDecl types when scanning model classes

---

transformation/common/src/main/java/org/jboss/tools/fuse/transformation/MapperConfiguration.java
transformation/common/src/main/java/org/jboss/tools/fuse/transformation/dozer/DozerMapperConfiguration.java
transformation/common/src/main/java/org/jboss/tools/fuse/transformation/dozer/DozerUtil.java
transformation/common/src/test/java/org/jboss/tools/fuse/transformation/dozer/DozerMapperConfigurationTest.java
transformation/common/src/test/resources/org/jboss/tools/fuse/transformation/dozer/abc2abc.xml
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/TransformationConfig.java

https://issues.jboss.org/browse/FUSETOOLS-1379

FUSETOOLS-1379 Class and index mappings are wrong in certain cases

---

transformation/common/src/main/java/org/jboss/tools/fuse/transformation/MapperConfiguration.java
transformation/common/src/main/java/org/jboss/tools/fuse/transformation/dozer/DozerMapperConfiguration.java
transformation/common/src/test/java/org/jboss/tools/fuse/transformation/dozer/DozerMapperConfigurationTest.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/TransformationConfig.java

https://issues.jboss.org/browse/FUSETOOLS-1355

FUSETOOLS-1355 Automatically map parent collections when a child field is mapped

---

transformation/common/src/main/java/org/jboss/tools/fuse/transformation/dozer/DozerMapperConfiguration.java
transformation/common/src/test/java/org/jboss/tools/fuse/transformation/dozer/DozerMapperConfigurationTest.java

https://issues.jboss.org/browse/FUSETOOLS-1398

FUSETOOLS-1398 Parent type not set correctly for indexed variable mappings

---

transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/TransformationEditor.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingDetailViewer.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingViewer.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/TargetTabFolder.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/dozer/DozerFileTypeHelper.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/dozer/DozerNamespaceHandler.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/CamelFileTypeHelper.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/CanceledDialogException.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/MappingPlaceholder.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/TestGenerator.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/Util.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/OtherPage.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/TransformTestWizardPage.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/XMLPage.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/XformWizardPage.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/wizards/NewTransformationTestWizard.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/wizards/NewTransformationWizard.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/extensions/DataTransformationPaletteEntry.java

FUSETOOLS-1410: Scalar to vector mapping - Cancel button creates a mapping

---

transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/SourceTabFolder.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/TargetTabFolder.java

Also fixed bug with https://github.com/fusesource/fuseide/pull/358

FUSETOOLS-1334: Allow to create a transformation via drag&drop from target to source

---

core/plugins/org.fusesource.ide.imports/src/org/fusesource/ide/imports/sap/JCo3ImportSettings.java

[FUSETOOLS-1357] Fixed separator used for zip file

---

transformation/plugins/org.jboss.tools.fuse.transformation.editor/OSGI-INF/l10n/bundle.properties
transformation/plugins/org.jboss.tools.fuse.transformation.editor/plugin.xml
transformation/plugins/org.jboss.tools.fuse.transformation.editor/schema/org.jboss.tools.fuse.transformation.editor.function.exsd
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/Activator.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/TransformationEditor.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/AddCustomFunctionDialog.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/AddFunctionDialog.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/FieldDialog.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingDetailViewer.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingViewer.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/SWTValueUpdater.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/TransformationConfig.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/Util.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/TransformTestWizardPage.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/wizards/NewTransformationTestWizard.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/wizards/NewTransformationWizard.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/resources/org/jboss/tools/fuse/transformation/editor/Function.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/resources/org/jboss/tools/fuse/transformation/editor/function/StringFunctions.java

Provides built-in functions with no additional arguments

Initial implementation of FUSETOOLS-1347

---

transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/wizards/NewTransformationWizard.java

This is 7.3.x only, not on master with Mars where it seems to work as expected.

FUSETOOLS-1443 - fixing issue with camel file selection in wizard

---

transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingDetailViewer.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/ModelViewer.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/PropertyDialog.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/Util.java

FUSETOOLS-1470: NPE changing property in function to one with different type

---

transformation/common/src/main/java/org/jboss/tools/fuse/transformation/dozer/DozerMapperConfiguration.java
transformation/common/src/test/java/org/jboss/tools/fuse/transformation/dozer/DozerMapperConfigurationTest.java

https://issues.jboss.org/browse/FUSETOOLS-1473

FUSETOOLS-1473 Automatic creation of parent mapping fails when field is not immediate child of collection

---

editor/plugins/org.fusesource.ide.camel.editor/META-INF/MANIFEST.MF
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/AdvancedEndpointPropertiesSection.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/DetailsSection.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/FusePropertySection.java
editor/tests/org.fusesource.ide.camel.editor.tests/META-INF/MANIFEST.MF
editor/tests/org.fusesource.ide.camel.editor.tests/src/org/fusesource/ide/camel/editor/CamelEditorTestSuite.java
editor/tests/org.fusesource.ide.camel.editor.tests/src/org/fusesource/ide/camel/editor/properties/FusePropertySectionTest.java

Mandatory parameter property labels appear in red with an asterisk (FUSETOOLS-1577)

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelDesignEditor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelEditor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelGlobalConfigEditor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/behaviours/CamelDiagramBehaviour.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/behaviours/CamelPersistencyBehaviour.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/commands/DiagramOperations.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/commands/ImportCamelContextElementsCommand.java

Editor
Precise to user in Diagram view that he needs to fix the file in Source
tab

Improve error feedback when opening an invalid XML file with Camel Route

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/AdvancedEndpointPropertiesSection.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/DetailsSection.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/FusePropertySection.java

Use indent layout data to have less cropped decorators (see

---

core/plugins/org.fusesource.ide.help/Fabric.html
core/plugins/org.fusesource.ide.help/IDU-CXF.html
core/plugins/org.fusesource.ide.help/IDU-LDAP.html
core/plugins/org.fusesource.ide.help/RiderTutorialCBR.html
core/plugins/org.fusesource.ide.help/RiderTutorialCreate.html
core/plugins/org.fusesource.ide.help/cxfComp.html
editor/plugins/org.fusesource.ide.branding/src/org/fusesource/ide/branding/wizards/NewCamelXmlWizard.java
editor/plugins/org.fusesource.ide.catalogs/xsd/fuse/camel-cxf-2.15.1.redhat-620133-blueprint.xsd

Use https value for xsd location to avoid error validation by WTP (see

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelEndpoint.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelFile.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelRouteElement.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/IFuseDetailsPropertyContributor.java
editor/plugins/org.fusesource.ide.camel.editor/plugin.xml
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/FusePropertySection.java

Details property section
we also avoid to trigger showing it when Connection are selected

FUSETOOLS-1643 - When Nothing is selected on the diagram, hide the

---

core/plugins/org.fusesource.ide.foundation.core/META-INF/MANIFEST.MF
core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/CamelUtils.java

CamelContentType
It allows to find Camel Context files for Wildfly archetypes too

FUSETOOLS-1456 - Search in all folders of the Project for a

---

transformation/plugins/org.jboss.tools.fuse.transformation.core/src/org/jboss/tools/fuse/transformation/core/model/xml/XmlModelGenerator.java
transformation/tests/org.jboss.tools.fuse.transformation.core.tests.integration/META-INF/MANIFEST.MF
transformation/tests/org.jboss.tools.fuse.transformation.core.tests.integration/src/main/java/org/jboss/tools/fuse/transformation/core/model/xml/XmlModelGeneratorIT.java

several namespaces
see also FUSETOOLS-1463

FUSETOOLS-1616 - Support XSD generation from xml instance containing

---

editor/plugins/org.fusesource.ide.launcher.ui/src/org/fusesource/ide/launcher/ui/launch/CustomLaunchConfigurationLabelProvider.java
editor/plugins/org.fusesource.ide.launcher.ui/src/org/fusesource/ide/launcher/ui/launch/ExecutePomAction.java
editor/plugins/org.fusesource.ide.launcher.ui/src/org/fusesource/ide/launcher/ui/launch/ExecutePomActionNoTests.java
editor/plugins/org.fusesource.ide.launcher.ui/src/org/fusesource/ide/launcher/ui/launch/ExecutePomActionSupport.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/run/util/MavenLaunchUtils.java

FUSETOOLS-1220 - Register and reuse Launch Configurations for Local

---

transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/JavaPage.java

Java Wizardpage
so now user won't be able to select a "bad class" and then have a CNFE
I think that a bunch of Integration worth to be written, to ensure also no regression on https://issues.jboss.org/browse/FUSETOOLS-1454

FUSETOOLS-1474 Provide Only Available Class Dependency In Transformation

---

servers/plugins/org.fusesource.ide.server.karaf.core/.settings/org.moreunit.prefs
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/Karaf2xStartupLaunchConfigurator.java
servers/tests/org.fusesource.ide.server.karaf.core.tests/.classpath
servers/tests/org.fusesource.ide.server.karaf.core.tests/.project
servers/tests/org.fusesource.ide.server.karaf.core.tests/.settings/org.eclipse.jdt.core.prefs
servers/tests/org.fusesource.ide.server.karaf.core.tests/META-INF/MANIFEST.MF
servers/tests/org.fusesource.ide.server.karaf.core.tests/build.properties
servers/tests/org.fusesource.ide.server.karaf.core.tests/pom.xml
servers/tests/org.fusesource.ide.server.karaf.core.tests/src-test/org/fusesource/ide/server/karaf/core/server/subsystems/Karaf2xStartupLaunchConfiguratorTest.java
servers/tests/pom.xml

FUSETOOLS-1257 - Overrides Launch Configuration with JVM Server Runtime

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/catalog/components/Component.java
editor/plugins/org.fusesource.ide.camel.editor/META-INF/MANIFEST.MF
editor/plugins/org.fusesource.ide.camel.editor/plugin.xml
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelGlobalConfigEditor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/dialogs/GlobalConfigElementsSelectionDialog.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/create/ext/CreateConnectorFigureFeature.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/provider/GlobalEndpointContributor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/wizards/AddGlobalEndpointWizard.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/wizards/pages/ComponentLabelProvider.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/wizards/pages/GlobalEndpointWizardPage.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/UIMessages.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/l10n/messages.properties
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/AdvancedPropertiesFilter.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/provider/DataFormatContributor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/provider/ext/GlobalConfigurationTypeWizard.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/provider/ext/ICustomGlobalConfigElementContribution.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/wizards/NewDataFormatWizard.java
editor/tests/org.fusesource.ide.camel.editor.tests/src-test/java/org/fusesource/ide/camel/editor/globalconfiguration/provider/GlobalEndpointContributorTest.java
editor/tests/org.fusesource.ide.camel.editor.tests/src-test/java/org/fusesource/ide/camel/editor/globalconfiguration/wizards/pages/ComponentLabelProviderTest.java

there is still a lot to improve but it allows to create a new endpoint at least.
I want to be sure that I'm going in teh right direction and some code changes might impact other development (passing a CamelFile instead of a Document)

Fusetools 1705 add global endpoint

---

editor/plugins/org.fusesource.ide.camel.editor/META-INF/MANIFEST.MF
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/wizards/pages/ComponentGroupedByTagsTreeContenProvider.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/wizards/pages/ComponentLabelProvider.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/wizards/pages/ComponentListTreeContentProvider.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/wizards/pages/ComponentManager.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/wizards/pages/GlobalEndpointWizardPage.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/UIMessages.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/l10n/messages.properties
editor/tests/org.fusesource.ide.camel.editor.tests.integration/META-INF/MANIFEST.MF
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/globalconfiguration/wizards/pages/ComponentGroupedByTagsTreeContenProviderIT.java
editor/tests/org.fusesource.ide.camel.editor.tests/src-test/java/org/fusesource/ide/camel/editor/globalconfiguration/wizards/pages/ComponentManagerTest.java

FUSETOOLS-1711 - Add option to group components by categories/tags

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/wizards/pages/ComponentNameAndTagPatternFilter.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/wizards/pages/GlobalEndpointWizardPage.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/UIMessages.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/l10n/messages.properties
editor/tests/org.fusesource.ide.camel.editor.tests/META-INF/MANIFEST.MF
editor/tests/org.fusesource.ide.camel.editor.tests/src-test/java/org/fusesource/ide/camel/editor/globalconfiguration/wizards/pages/ComponentNameAndTagPatternFilterTest.java

https://github.com/fusesource/fuseide/pull/478 needs to be reviewed and merged before
-->Rebased: ready for review :-)

Fusetools 1716 search filter on name description and tag

---

core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/xml/XMLCamelRoutesValidator.java
core/tests/org.fusesource.ide.camel.validation.tests.integration/src/org/fusesource/ide/camel/validation/xml/XMLCamelRoutesValidatorIT.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/dialogs/GlobalConfigSupport.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/CamelGlobalConfigEditor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/GlobalConfigContentProvider.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/GlobalConfigLabelProvider.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/dataformat/provider/DataFormatContributor.java
editor/plugins/org.fusesource.ide.project/plugin.xml
editor/plugins/org.fusesource.ide.project/src/org/fusesource/ide/project/decorator/CamelProblemDecorator.java

review and merge https://github.com/fusesource/fuseide/pull/482 before

Fusetools 1225 provide validation marker on global page tree

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/CamelGlobalConfigEditor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/AdvancedPropertiesFilter.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/FusePropertySection.java

https://github.com/fusesource/fuseide/pull/484 needs to be reviewed and merged before

Fusetools 172 fix selection issue when comingfrom another view

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/CamelGlobalConfigEditor.java

https://github.com/fusesource/fuseide/pull/485 needs to be reviewed and merged before

Fusetools 1725 improve delete button enablement

---

pom.xml

Rebuilt fuseide and fuseide/targetplatform with updated JBTIS TP

JBTIS-616 - bump JBTIS TP to 4.3.1.CR1

---

transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/TransformationEditor.java

after that, it goes further but I have some org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[message1.xml] with the root cause: "java.lang.ClassNotFoundException: org.apache.camel.spi.DataFormatName"
It should a different issue. what do you think @jpav ?

FUSETOOLS-1533 - Don't override default resources folder

---

core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/CamelIOHandlerIT.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/FuseProject.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/resources/unmarshalSample.xml

- add the test
- extract a Rule to create the project and write more fine grained tests
about Unmarshal component model loading

FUSETOOLS-1789 - Add non-regression test for Unmarshal component

---

core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/util/PropertiesUtilsTestIT.java

Use Better naming for parameterized tests

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelFile.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/META-INF/MANIFEST.MF
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/CamelGlobalConfigEditor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/dataformat/provider/DataFormatContributor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/endpoint/provider/GlobalEndpointContributor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/provider/ext/ICustomGlobalConfigElementContribution.java

- Modify interface to have access to CamelFile
- Support selection of Element in the Tree

FUSETOOLS-1778 - Improve support of Global Elements

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/dialogs/GlobalConfigElementsSelectionDialog.java

FUSETOOLS-1849 - Expand Tree by default

---

editor/plugins/org.fusesource.ide.launcher.ui/src/org/fusesource/ide/launcher/ui/launch/ExecutePomActionSupport.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/launching/CamelSourceLookupDirector.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/launching/CamelSourcePathComputerDelegate.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/CamelDebugElement.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/CamelEndpointBreakpoint.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/values/BaseCamelValue.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/values/CamelDebuggerValue.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/values/CamelExchangeValue.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/values/CamelHeadersValue.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/values/CamelMessageValue.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/values/CamelProcessorValue.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/util/CamelDebugUtils.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/run/launching/FuseMavenLaunchDelegate.java
editor/tests/org.fusesource.ide.launcher.tests/src/test/java/org/fusesource/ide/launcher/debug/model/values/CamelDebuggerValueTest.java
editor/tests/org.fusesource.ide.launcher.tests/src/test/java/org/fusesource/ide/launcher/debug/model/values/CamelExchangeValueTest.java
editor/tests/org.fusesource.ide.launcher.tests/src/test/java/org/fusesource/ide/launcher/debug/model/values/CamelHeadersValueTest.java
editor/tests/org.fusesource.ide.launcher.tests/src/test/java/org/fusesource/ide/launcher/debug/model/values/CamelMessageValueTest.java
editor/tests/org.fusesource.ide.launcher.tests/src/test/java/org/fusesource/ide/launcher/debug/model/values/CamelProcessorValueTest.java
editor/tests/org.fusesource.ide.project.tests.integration/META-INF/MANIFEST.MF
editor/tests/org.fusesource.ide.project.tests.integration/src/main/java/org/fusesource/ide/project/camel/integration/ui/CamelProjectWizardIT.java

- fix Debug mode
- added unit test ensuring creation of Eclipse DebugVariable with emtpy
values
- starting work to have an Integration tests

FUSETOOLS-1846 - Avoid NPE when no timestamp provided in Exchange

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/io/CamelIOHandler.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/AbstractCamelModelElement.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelContextElement.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelFile.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/GlobalDefinitionCamelModelElement.java
core/plugins/org.fusesource.ide.foundation.ui/src/org/fusesource/ide/foundation/ui/util/Selections.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/CamelIOHandlerIT.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/model/GlobalDefinitionsIT.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/resources/withGlobalDefinitionSample.xml
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/CamelGlobalConfigEditor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/GlobalConfigContentProvider.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/GlobalConfigLabelProvider.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/dataformat/provider/DataFormatContributor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/endpoint/provider/GlobalEndpointContributor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/provider/ext/ICustomGlobalConfigElementContribution.java
editor/tests/org.fusesource.ide.camel.editor.tests/src/test/java/org/fusesource/ide/camel/editor/globalconfiguration/endpoint/provider/GlobalEndpointContributorTest.java

- rely on it for extension points for Global Configuration Editor

FUSETOOLS-1861 - Introduce new Global Definition model element

---

editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/CamelStackFrame.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/values/CamelExchangeValue.java
editor/tests/org.fusesource.ide.launcher.tests/src/test/java/org/fusesource/ide/launcher/debug/model/values/CamelDebuggerValueTest.java
editor/tests/org.fusesource.ide.launcher.tests/src/test/java/org/fusesource/ide/launcher/debug/model/values/CamelExchangeValueTest.java
editor/tests/org.fusesource.ide.launcher.tests/src/test/java/org/fusesource/ide/launcher/debug/model/values/CamelProcessorValueTest.java

add non-regression tests for similar elements

FUSETOOLS-1862 - Fix hasVariables method

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/AbstractCamelModelElement.java
core/plugins/org.fusesource.ide.foundation.ui/src/org/fusesource/ide/foundation/ui/tree/NodeSupport.java
jmx/plugins/org.fusesource.ide.jmx.camel/src/org/fusesource/ide/jmx/camel/navigator/EndpointsNode.java
jmx/plugins/org.fusesource.ide.jmx.camel/src/org/fusesource/ide/jmx/camel/navigator/RoutesNode.java
jmx/plugins/org.fusesource.ide.jmx.diagram.view/META-INF/MANIFEST.MF
jmx/plugins/org.fusesource.ide.jmx.diagram.view/src/org/fusesource/ide/jmx/diagram/view/DiagramView.java
jmx/plugins/org.fusesource.ide.jmx.diagram.view/src/org/fusesource/ide/jmx/diagram/view/NodeGraphContentProvider.java
jmx/plugins/org.fusesource.ide.jmx.diagram.view/src/org/fusesource/ide/jmx/diagram/view/RouteGraphContentProvider.java

I wasn't able to write Unit tests yet due to JMX Nodes which are connected and that I wasn't able to mock

FUSETOOLS-1847 - Reconnect Messages and Diagram View and display all

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/utils/CamelUtils.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/utils/MavenUtils.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/TransformationEditor.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/CamelEndpointSelectionDialog.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingDetailViewer.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/Util.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/Hl7Page.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/JSONPage.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/Model.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/StartPage.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/TransformTestWizardPage.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/wizards/NewTransformationWizard.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/extensions/TransformationDblClickHandler.java

I know there is no test(s) for this, but these changes require PDE tests, and I have to address that in general for the entire project, which will take more time than I want to spend right now for this bug.

FUSETOOLS-1830: If no java source folder exists, the data transformation wizard fails

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/AbstractCamelModelElement.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/CamelIOHandlerIT.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/resources/emptyOtherwiseSample.xml

@lhein Do you have other use cases in mind that I should in the suite?

FUSETOOLS-1811 - Don't remove empty Otherwise node

---

editor/plugins/org.fusesource.ide.camel.editor/.options
editor/plugins/org.fusesource.ide.camel.editor/build.properties
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/DocumentationSection.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/NodeSectionSupport.java

these logs occurs very often and have little interest
@lhein unless I miss a point?

FUSETOOLS-1901 - Remove some logs

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/util/BasicProjectCreator.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/FuseIntegrationProjectWizard.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardLocationPage.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java

- also add improved validation when using a specific folder inside the
workspace

FUSETOOLS-1890 - Support creation of project outside of workspace

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/FuseIntegrationProjectCreatorRunnable.java

there was already target folder ignored, need to ignore also bin one
it will avoid the random failures on CI (and fix a real issue)

FUSETOOLS-1922 - Avoid to use File from bin folder

---

editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java

due to bad config of UI environment on CI

FUSETOOLS-1923 - Loop to ignore random exceptions in UI

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/creators/AbstractClassBasedParameterPropertyUICreator.java

now support also Java-but-not-Maven project type

FUSETOOLS-1921 - Avoid NPE when Maven project not found

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/adopters/configurators/MavenTemplateConfigurator.java

FUSETOOLS-1942 - wait for all job to finish to avoid random failures

---

templates/blank/blank-java/pom.xml
templates/blank/blank-spring/pom.xml
templates/medium/cxf-contract-first/medium-fuse-cxf-contract-first-blueprint/pom.xml
templates/simple/amq/simple-fuse-activemq-blueprint/pom.xml
templates/simple/amq/simple-fuse-activemq-java/pom.xml
templates/simple/cbr/simple-fuse-cbr-spring/pom.xml

in order to generate a valid MANIFEST.MF

FUSETOOLS-1951 - Fix Maven bundle plugin configuration

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/navigator/CamelCtxNavActionProvider.java

To be bale to Open Route from Project Explorer when editor already
opened with 'Source' or 'Configuration' tab selected

FUSETOOLS-1954 - Fix NPE

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/AbstractCamelModelElement.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelRouteElement.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelFilesFinder.java
core/tests/org.fusesource.ide.camel.model.service.core.tests/src/test/java/org/fusesource/ide/camel/model/service/core/model/GenerateNewIDTest.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/run/launching/CamelRunMavenLaunchDelegate.java
editor/plugins/org.fusesource.ide.project/src/org/fusesource/ide/project/providers/CamelVirtualFolder.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/maven/CamelProjectConfigurator.java

/!\ we are looking unique ID on saved model files. If one other camel
file in the same project has been modified, two ids can be identic.

FUSETOOLS-1928 - Generate Unique ID for routes in same project

---

editor/plugins/org.fusesource.ide.launcher.ui/src/org/fusesource/ide/launcher/ui/launch/ExecutePomAction.java
editor/plugins/org.fusesource.ide.launcher.ui/src/org/fusesource/ide/launcher/ui/launch/ExecutePomActionSupport.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/org/fusesource/ide/projecttemplates/tests/integration/wizards/LaunchFromCamelContextFileIT.java

FUSETOOLS-2000 - Reuse Launch Configuration when Launched from a

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/AbstractCamelModelElement.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelDesignEditor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/custom/GoIntoContainerFeature.java

- avoid NPE
- ensure that the selectedContainer attribute is updated when "going up"
I don't see how to write meaningful test except by writing a UI one.

FUSETOOLS-1955 - Fix Go into feature

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/io/CamelIOHandler.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelFile.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/CamelIOHandlerIT.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/resources/JMXBeanAnswer--camelContext--11--11.xml

- fix regression introduced with FUSETOOLS-1987
- add tests to ensure loading of xml currently provided by JMX is
correctly loaded

FUSETOOLS-2022 - Fix Regression And Add Test

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardTemplatePage.java

- use Text instead of StyledText
- remaining little issue for Search icon place on filter Text but should
be an SWT issue

FUSETOOLS-1875 - respect disablement of template description

---

editor/plugins/org.fusesource.ide.launcher.ui/META-INF/MANIFEST.MF
editor/plugins/org.fusesource.ide.launcher.ui/plugin.xml
editor/plugins/org.fusesource.ide.launcher.ui/src/org/fusesource/ide/launcher/ui/propertytester/CamelLocalLaunchPropertyTester.java
editor/tests/org.fusesource.ide.launcher.ui.tests/src/test/java/org/fusesource/ide/launcher/ui/propertytester/CamelLocalLaunchPropertyTesterTest.java

FUSETOOLS-1977 - Enable local launch only when camel-maven-plugin

---

templates/medium/eap-wildfly/camel-test-cdi/README.md
templates/medium/eap-wildfly/camel-test-cdi/pom.xml
templates/medium/eap-wildfly/camel-test-cdi/src/main/java/org/test/MyBean.java
templates/medium/eap-wildfly/camel-test-cdi/src/main/java/org/test/MyRouteBuilder.java
templates/medium/eap-wildfly/camel-test-cdi/src/main/java/org/test/MyServlet.java
templates/medium/eap-wildfly/camel-test-cdi/src/main/webapp/WEB-INF/beans.xml
templates/medium/eap-wildfly/camel-test-cdi/src/test/java/org/test/MyTest.java
templates/medium/eap-wildfly/camel-test-cdi/src/test/resources/arquillian.xml
templates/medium/eap-wildfly/camel-test-spring/README.md
templates/medium/eap-wildfly/camel-test-spring/pom.xml
templates/medium/eap-wildfly/camel-test-spring/src/main/java/org/test/MyBean.java
templates/medium/eap-wildfly/camel-test-spring/src/main/java/org/test/MyServlet.java
templates/medium/eap-wildfly/camel-test-spring/src/main/webapp/META-INF/jboss-camel-context.xml
templates/medium/eap-wildfly/camel-test-spring/src/test/java/org/test/MyTest.java
templates/medium/eap-wildfly/camel-test-spring/src/test/resources/arquillian.xml

Adds two new examples from James Netherton and updates the pom on the existing EAP example. Still a work in progress, but wanted to get them up and into github for more public consumption by the team.

FUSETOOLS-1983 - adding two new templates

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/AbstractCamelModelElement.java
core/tests/org.fusesource.ide.camel.model.service.core.tests/src/test/java/org/fusesource/ide/camel/model/service/core/model/AbstractCamelModelElementTest.java

- avoid issues when something other than an endpoint have a parameter
named "uri"
I checked the other places , the isEndpointElement is called and in fact it was leading to issues too. So other parts are fixed too :-)

FUSETOOLS-2040 - Improve definition of endpoints

---

pom.xml

@lhein @apupier - this works for me - cleaned out my local m2 repo and build fuse tooling and the fuse TP

JBTIS-844 - update fuse tooling to 4.3.3.Final and tycho to 0.26

---

editor/plugins/org.fusesource.ide.projecttemplates/META-INF/MANIFEST.MF
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/maven/CamelProjectConfigurator.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForEAPSpringIT.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java

otherwise they are not played during build

Integration Test requires to follow *IT pattern

---

editor/plugins/org.fusesource.ide.project/src/org/fusesource/ide/project/decorator/CamelProblemDecorator.java

FUSETOOLS-2090 - Check if resource still exists before trying to get the

---

pom.xml

Fuse Tooling and Fuse Tooling TP both build ok.

FUSETOOLS-2103 - bump jbtis tp to 4.3.4.Final

---

editor/plugins/org.fusesource.ide.camel.editor/.settings/org.moreunit.prefs
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/component/wizard/NewEndpointIdValidator.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/component/wizard/SelectComponentWizardPage.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/genericEndpoint/GenericEndpointFigureFeature.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/genericEndpoint/SelectEndpointWizard.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/endpoint/wizards/AddGlobalEndpointWizard.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/UIMessages.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/l10n/messages.properties
editor/tests/org.fusesource.ide.camel.editor.tests/src/test/java/org/fusesource/ide/camel/editor/component/wizard/NewEndpointIdValidatorTest.java

FUSETOOLS-1763 - provide validation for Id unicity in "new generic

---

transformation/plugins/org.jboss.tools.fuse.transformation.core/src/org/jboss/tools/fuse/transformation/core/model/xml/XmlModelGenerator.java

FUSETOOLS-2157 - Set accessExternalFileAccess to all and log parse

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelFilesFinder.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/FuseIntegrationProjectCreatorRunnable.java

FUSETOOLS-2117 - Fix opening of editor on project creation when Spring

---

editor/plugins/org.fusesource.ide.project/META-INF/MANIFEST.MF
editor/plugins/org.fusesource.ide.project/src/org/fusesource/ide/project/providers/CamelFilesContentProvider.java
editor/plugins/org.fusesource.ide.project/src/org/fusesource/ide/project/providers/CamelVirtualFolder.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/FuseIntegrationProjectCreatorRunnable.java

https://github.com/fusesource/fuseide/pull/731 needs to be merged before

Fusetools 2117 set default editor for next opening

---

transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/wizards/NewTransformationWizard.java

I don't like the fact that this creates a flashing progress dialog as we rename each package, but it does resolve the issue. That said, there is still a problem with the generated code not building correctly. So I'm open to suggestions here.

FUSETOOLS-2123 - fixing refactoring issue

---

transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/TransformationEditor.java

I hit InterruptedException 2 times (out of 4) during investigation so I improved robustness

FUSETOOLS-2138 - be more robust against InterruptedException

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/creators/modifylisteners/number/AbstractNumberModifyListener.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/META-INF/MANIFEST.MF
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/properties/creators/NumberParameterPropertyUICreatorIT.java

Not sure why this has taken the whole file and not just added the few lines that were changed.

FUSETOOLS-1898 - fixing issue with red background on integer parms

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/adopters/configurators/MavenTemplateConfigurator.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/maven/CamelProjectConfigurator.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/util/JobWaiterUtil.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/FuseIntegrationProjectCreatorRunnable.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/META-INF/MANIFEST.MF
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/ProjectTemplatesIntegrationTestsActivator.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/CamelProjectConfiguratorIT.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForSimpleIT.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/LaunchFromCamelContextFileIT.java

- factorize code to wait jobs to reuse the workaround for Eclipse bugs

FUSETOOLS-2133 - Avoid Job interruption failing the Maven Configuration

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/add/AddFlowFeature.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/add/AddNodeFeature.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/custom/LayoutDiagramFeature.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/misc/LayoutNodeFeature.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/misc/PasteNodeFeature.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/misc/UpdateNodeFeature.java

Code cleaning during preliminary investigation on FUSETOOLS-2160

Clean code

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/AbstractCamelModelElement.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/create/ext/CreateFigureFeature.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/misc/DirectEditNodeFeature.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/misc/MoveNodeFeature.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/misc/UpdateNodeFeature.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/provider/CamelFeatureProvider.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/AbstractCamelEditorIT.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/CamelEditorIT.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/CamelEditorMoveIT.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/moveInRoute.xml

current limitation:
- doesn't support the insert/append/prepend
I think that the current state is coherent and is adding nice value.
I will implement the insert/append/prepend in another PR

FUSETOOLS-2160 - Allow move nodes between containers

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/misc/MoveNodeFeature.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/CamelEditorMoveIT.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/moveInRoute.xml

please review https://github.com/fusesource/fuseide/pull/765 before this one

Fusetools 2160 allow move and insert

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/l10n/messages.properties
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardLocationPage.java

This is to avoid problems on Windows.

FUSETOOLS-1738 Validate the project name in fuseProjectwizard ignoring case sensitive

---

core/features/org.fusesource.ide.core.feature/feature.properties
editor/features/org.fusesource.ide.camel.editor.feature/feature.properties
editor/plugins/org.fusesource.ide.camel.editor/schema/org.fusesource.ide.editor.dblClickHandler.exsd
editor/plugins/org.fusesource.ide.camel.editor/schema/org.fusesource.ide.editor.globalConfigContributor.exsd
editor/plugins/org.fusesource.ide.camel.editor/schema/org.fusesource.ide.editor.paletteContributor.exsd
editor/plugins/org.fusesource.ide.projecttemplates/schema/org.fusesource.ide.projecttemplates.templates.exsd
jmx/features/org.fusesource.ide.jmx.feature/feature.properties
servers/features/org.fusesource.ide.server.extensions.feature/feature.properties
transformation/features/org.jboss.tools.fuse.transformation.feature/feature.properties

update only for copyrights for global elements:
- ranges on features
- range on extension point

FUSETOOLS-2232 - Update year from 2016 to 2017

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/catalog/CamelModelFactory.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/AbstractCamelModelElement.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelFile.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelComponentUtils.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/LanguageUtils.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/PropertiesUtils.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/model/EipChecksIT.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/util/PropertiesUtilsTestIT.java
core/tests/org.fusesource.ide.camel.model.tests/src/main/java/org/fusesource/ide/camel/commons/ValidateSyntaxInCatalogIT.java
core/tests/org.fusesource.ide.camel.tests.util/src/org/fusesource/ide/camel/tests/util/CamelModelRegistrationRule.java
core/tests/org.fusesource.ide.camel.validation.tests.integration/src/org/fusesource/ide/camel/validation/xml/XMLCamelRoutesValidatorIT.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/dialogs/ConditionalBreakpointEditorDialog.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/create/ext/CreateFigureFeature.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/genericEndpoint/GenericEndpointFigureFeature.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/CamelGlobalConfigEditor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/dataformat/provider/DataFormatContributor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/endpoint/provider/GlobalEndpointContributor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/preferences/CamelEditorPreferencePage.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/AdvancedPropertiesFilter.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/FusePropertySection.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/provider/ProviderHelper.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/provider/ToolBehaviourProvider.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/utils/NodeUtils.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/CamelEditorIT.java
transformation/plugins/org.jboss.tools.fuse.transformation.core/src/org/jboss/tools/fuse/transformation/core/camel/CamelConfigBuilder.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/ExpressionDialog.java

please review and merge https://github.com/fusesource/fuseide/pull/792 first
EDIT: review and merge done, rebased done

Fusetools 2154 configure palette and properties to use correct runtime provider

---

editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/CamelDebugTarget.java

Detect if breakpoint manager is disabled  
then disable all breakpoints

FUSETOOLS-1802

---

tools/ide-catalog-generator/src/main/java/org/fusesource/ide/catalog/generator/model/component/ComponentModel.java

- remove unused field
- use genericity
- specify JavaSE 1.8

FUSETOOLS-2239 - Clean code during investigation

---

editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/util/camel/CamelFacetVersionChangeDelegateIT.java

the way to calculate the AMQ version need to be updated as the latest
version is now a productized one

FUSETOOLS-2239 FUSETOOLS-2237 mid-air collision

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/dataformat/wizards/NewDataFormatWizard.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/utils/MavenUtils.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/globalconfiguration/dataformat/wizards/NewDataFormatWizardIT.java
editor/tests/org.fusesource.ide.camel.editor.tests/src/test/java/org/fusesource/ide/camel/editor/utils/MavenUtilsTest.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/wizards/NewTransformationWizard.java

- also use a lighter setup for the project in Integration tests which
should divide test execution time by 3.

FUSETOOLS-2245 - Improve test to really check for depdency added

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/utils/MavenUtils.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/adopters/configurators/MavenTemplateConfigurator.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/maven/CamelProjectConfigurator.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java

re-enable test for FUSE 6.3.0.R1 too(FUSETOOLS-2251)
want to see results on a clean environment

FUSETOOLS-2252 - avoid touching pom at wrong time

---

editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot/.settings/fusetooling/Deploy %%%PLACEHOLDER_PROJECTNAME%%% on OpenShift.launch

fabric8-maven-plugin has changed the default so need to specify it in
the launch configuration now.

FUSETOOLS-2271 - specify usage of docker

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelFilesFinder.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/FuseProject.java
editor/plugins/org.fusesource.ide.project/src/org/fusesource/ide/project/providers/CamelVirtualFolder.java
editor/tests/org.fusesource.ide.project.tests.integration/META-INF/MANIFEST.MF
editor/tests/org.fusesource.ide.project.tests.integration/src/main/java/org/fusesource/ide/project/providers/CamelVirtualFolderIT.java

FUSETOOLS-2179 - Hide Camel files from Work folder in Camel Context

---

jmx/plugins/org.fusesource.ide.jmx.karaf/src/org/fusesource/ide/jmx/karaf/connection/KarafActiveJvm.java
jmx/plugins/org.fusesource.ide.jmx.karaf/src/org/fusesource/ide/jmx/karaf/navigator/osgi/BundleStatusLabelProvider.java
jmx/plugins/org.fusesource.ide.jmx.karaf/src/org/fusesource/ide/jmx/karaf/navigator/osgi/BundlesNode.java
jmx/plugins/org.fusesource.ide.jmx.karaf/src/org/fusesource/ide/jmx/karaf/navigator/osgi/BundlesTableSheetPage.java
jmx/plugins/org.fusesource.ide.jmx.karaf/src/org/fusesource/ide/jmx/karaf/navigator/osgi/BundlesTableView.java
jmx/plugins/org.fusesource.ide.jmx.karaf/src/org/fusesource/ide/jmx/karaf/navigator/osgi/CompositeDataPropertySource.java
jmx/plugins/org.fusesource.ide.jmx.karaf/src/org/fusesource/ide/jmx/karaf/navigator/osgi/ServicesTableSheetPage.java
jmx/plugins/org.fusesource.ide.jmx.karaf/src/org/fusesource/ide/jmx/karaf/navigator/osgi/TabularDataHelper.java

FUSETOOLS-2267 - Code cleaning

---

core/tests/org.fusesource.ide.camel.validation.tests.integration/src/org/fusesource/ide/camel/validator/marker/MarkersRemoverValidatorIT.java

avoid usage of Thread.sleep and rely on Job instead

FUSETOOLS-2276 - Stabilize test

---

editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/CamelDebugTarget.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java

- report Marker without severity as Error and as Warning to fail test
when it occurs

Avoid NPE in tests

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelComponentUtils.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/PropertiesUtils.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/AdvancedEndpointPropertiesSection.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/DetailsSection.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/properties/creators/TextParameterPropertyUICreatorIT.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/properties/creators/advanced/TextParameterPropertyUICreatorForAdvancedIT.java

no more bad data displayed and data loss but no user guidance (will need
to handle it in an enhancment request)

FUSETOOLS-2280 - Support char javatypes

---

servers/plugins/org.fusesource.ide.server.fuse.core/META-INF/MANIFEST.MF
servers/plugins/org.fusesource.ide.server.fuse.core/src/org/fusesource/ide/server/fuse/core/runtime/integration/FuseDownloadRuntimesProvider.java

I detected this issue by enabling errors on missing classes and resources after work on https://github.com/fusesource/fuseide/pull/858

Clean server fuse core

---

core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/ValidationResult.java
core/tests/org.fusesource.ide.camel.validation.tests.integration/META-INF/MANIFEST.MF
core/tests/org.fusesource.ide.camel.validation.tests.integration/src/org/fusesource/ide/camel/validator/marker/MarkersRemoverValidatorIT.java
editor/plugins/org.fusesource.ide.projecttemplates/META-INF/MANIFEST.MF
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/adopters/configurators/MavenTemplateConfigurator.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/util/BuildAndRefreshJobWaiterUtil.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/util/JobWaiterUtil.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/FuseIntegrationProjectCreatorRunnable.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/globalconfiguration/dataformat/wizards/NewDataFormatWizardIT.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/provider/ToolBehaviourProviderIT.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/CamelProjectConfiguratorIT.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java

the goal is to better understand why it is failing sometimes on CI

FUSETOOLS-2276 - provide more information in case of failure

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/CamelModelNotificationService.java

- check for editor non-nullity
- remove unused variable
- use genericity

FUSETOOLS-2296 - Avoid NPE in CamelNotificationService

---

editor/plugins/org.fusesource.ide.launcher.ui/src/org/fusesource/ide/launcher/ui/tabs/CamelContextFileTab.java

FUSETOOLS-2298 - Avoid FileNotFoundException in CamelContext Browse

---

editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/CamelDebugTarget.java

FUSETOOLS-2299 - avoid NPE when removing breakpoint while debugger is

---

editor/plugins/org.fusesource.ide.launcher.ui/src/org/fusesource/ide/launcher/ui/tabs/DebugJmxTab.java

also:
- factorize ModifyListener which is just refreshign the whole
LaunchConfigurationTab
- remove unused attributes
- use same catch clause for exception logging the same thing

FUSETOOLS-2297 - Add missing border for JMX Password field

---

editor/plugins/org.fusesource.ide.launcher.ui/src/org/fusesource/ide/launcher/ui/propertytester/CamelLocalLaunchPropertyTester.java

FUSETOOLS-2301 - Avoid NPE if project not in Maven cache or not a Maven

---

editor/plugins/org.fusesource.ide.project/src/org/fusesource/ide/project/CamelNatureTester.java

which is done by isAccessible()

FUSETOOLS-2303 - check if project is open and exists

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/PropertiesUtils.java
core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/model/RequiredPropertyValidator.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/AdvancedEndpointPropertiesSection.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/DetailsSection.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/FusePropertySection.java
editor/tests/org.fusesource.ide.camel.editor.tests/src/test/java/org/fusesource/ide/camel/editor/properties/AdvancedEndpointPropertiesSectionTest.java
editor/tests/org.fusesource.ide.camel.editor.tests/src/test/java/org/fusesource/ide/camel/editor/properties/DetailsSectionTest.java

FUSETOOLS-2314 - FUSETOOLS-2187 - Display DataFormat parameters in

---

editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot/pom.xml
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java

https://maven.repository.redhat.com/earlyaccess/all/ can be removed when https://issues.jboss.org/browse/OSFUSE-558 will be fixed

FUSETOOLS-2325 - Add missing maven repositories

---

servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/publish/jmx/KarafJMXPublisher.java

- check on more attributes for nullity
- provide logs to investigate in case of issue

FUSETOOLS-2329 - Imrpove robustness to NPE

---

pom.xml

see https://groups.google.com/forum/#!topic/sonarlint/TWk2_DRMLcw for
more details
it will avoid to have a lot of failed rules reported although it
shouldn't as it is test classes (such as "Define and throw a dedicated
exception instead of using a generic one.")
**/*Test.*,**/test/**/* is the default pattern used by Sonar, we need to add **/*IT.*

Include *IT classes as Test sources

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/PropertiesUtils.java
core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/Objects.java
core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/Strings.java
editor/plugins/org.fusesource.ide.branding/src/org/fusesource/ide/branding/wizards/NewCamelTestWizardPageTwo.java
jmx/plugins/org.fusesource.ide.jmx.karaf/src/org/fusesource/ide/jmx/karaf/connection/KarafServerConnection.java
servers/plugins/org.fusesource.ide.server.karaf.ui/src/org/fusesource/ide/server/karaf/ui/editor/ConnectionDetailsEditorSection.java
servers/plugins/org.fusesource.ide.server.karaf.ui/src/org/fusesource/ide/server/karaf/ui/runtime/KarafServerPorpertiesComposite.java

Fix primitives boxed just for String

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/provider/ProviderHelper.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/provider/ToolBehaviourProviderIT.java

"On Fallback" has been added for Hystrix

FUSETOOLS-2336 - Add Hystrix Routing EIP in the Palette

---

core/plugins/org.fusesource.ide.foundation.ui/src/org/fusesource/ide/foundation/ui/io/CamelContextNodeEditorInput.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelDesignEditor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelEditor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/behaviours/CamelDiagramBehaviour.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/behaviours/CamelPersistencyBehaviour.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/utils/ImageUtils.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/CamelDebugFacade.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/util/CamelDebugUtils.java
jmx/plugins/org.fusesource.ide.jmx.camel/src/org/fusesource/ide/jmx/camel/navigator/CamelContextNode.java

it allows to put breakpoint on a remote camel context.
They will be triggered if a Remote Camel Debug laucnh configuration has been used specifiying the correct - almost hidden - files.
So not perfect but it is now possible.
More to come in another PR with https://issues.jboss.org/browse/FUSETOOLS-2317

Fusetools 2307 graphical remote debug for jmx routes basic

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/jmx/camel/CamelFacadeSupport.java
core/plugins/org.fusesource.ide.foundation.ui/src/org/fusesource/ide/foundation/ui/actions/ConfigureColumnsDialog.java
core/plugins/org.fusesource.ide.foundation.ui/src/org/fusesource/ide/foundation/ui/chart/TableChartOptions.java
core/plugins/org.fusesource.ide.foundation.ui/src/org/fusesource/ide/foundation/ui/config/TableConfiguration.java
editor/plugins/org.fusesource.ide.branding/src/org/fusesource/ide/branding/wizards/project/AbstractCreateProjectJob.java
editor/plugins/org.fusesource.ide.branding/src/org/fusesource/ide/branding/wizards/project/FuseProjectWizardArchetypePage.java
editor/plugins/org.fusesource.ide.branding/src/org/fusesource/ide/branding/wizards/project/WorkingSetGroup.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/custom/CollapseFeature.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/outline/CamelModelOutlineContentProvider.java
jmx/plugins/org.fusesource.ide.jmx.activemq/src/org/fusesource/ide/jmx/activemq/internal/BrokerFacadeSupport.java
jmx/plugins/org.fusesource.ide.jmx.activemq/src/org/fusesource/ide/jmx/activemq/internal/RemoteBrokerFacadeSupport.java
transformation/plugins/org.jboss.tools.fuse.transformation.core/src/org/jboss/tools/fuse/transformation/core/dozer/DozerMapperConfiguration.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/ModelViewer.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/Util.java

Use isEmpty() to check Emptiness and not emptiness to improve

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelFileTemplateCreator.java
core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/xml/XmlEscapeUtility.java
core/plugins/org.fusesource.ide.imports/src/org/fusesource/ide/imports/sap/JCo3Archive.java
editor/plugins/org.fusesource.ide.branding/src/org/fusesource/ide/branding/wizards/NewCamelTestWizardPageOne.java
editor/plugins/org.fusesource.ide.branding/src/org/fusesource/ide/branding/wizards/project/FuseProjectWizardArchetypePage.java
editor/plugins/org.fusesource.ide.branding/src/org/fusesource/ide/branding/wizards/project/WorkingSetGroup.java
jmx/plugins/org.fusesource.ide.jmx.commons/src/org/fusesource/ide/jmx/commons/JmxTemplateSupport.java
jmx/plugins/org.fusesource.ide.jmx.karaf/src/org/fusesource/ide/jmx/karaf/connection/KarafJVMFacadeUtility.java
servers/plugins/org.fusesource.ide.server.fuse.ui/src/org/fusesource/ide/server/fuse/ui/FuseSharedImages.java
transformation/plugins/org.jboss.tools.fuse.transformation.core/src/org/jboss/tools/fuse/transformation/core/camel/EndpointHelper.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/Hl7Page.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/JSONPage.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/TransformTestWizardPage.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/XMLPage.java

which should improve performance

Avoid usage of old synchronized classes

---

editor/tests/org.fusesource.ide.launcher.tests.integration/src/main/java/org/fusesource/ide/launcher/tests/integration/remote/debug/ProjectWithDebugAvailableDeployedHelper.java
editor/tests/org.fusesource.ide.launcher.tests.integration/src/main/java/org/fusesource/ide/launcher/tests/integration/remote/debug/RemoteCamelLaunchConfigurationDelegateIT.java

it avoids to have it failing on windows

Clean test correctly

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/provider/ext/PaletteCategoryItemProvider.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardTemplatePage.java
jmx/plugins/org.fusesource.ide.jmx.commons/src/org/fusesource/ide/jmx/commons/views/messages/SelectionListenerForMessageView.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/ControllableKarafServerBehavior.java

Sonar Java analyzer has been updated and has reported new critical issues about empty statements

Remove empty statements

---

transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/Hl7Page.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/JSONPage.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/wizards/NewTransformationWizard.java

Reverts jbosstools/jbosstools-fuse#935

Revert "FUSETOOLS-2374: Fix issues in JSONPage found by SonarQube"

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/create/ext/CreateFigureFeature.java

(Not critical for 9.2, but would be good to go for 9.3 or 10.0)

FUSETOOLS-2390 - fixing issue with create feature

---

editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/CamelDebugTarget.java

Good for 9.3 or 10. Haven't been able to reproduce the issue locally, but I suspect the file doesn't exist and that is the cause of the NPE.

FUSETOOLS-2386 - should fix the NPE

---

core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/build.properties
core/tests/org.fusesource.ide.camel.model.service.core.tests/build.properties
core/tests/org.fusesource.ide.camel.model.tests/build.properties
core/tests/org.fusesource.ide.camel.tests.util/build.properties
core/tests/org.fusesource.ide.camel.validation.tests.integration/build.properties
core/tests/org.fusesource.ide.camel.validation.tests/build.properties
editor/tests/org.fusesource.ide.camel.editor.tests.integration/build.properties
editor/tests/org.fusesource.ide.camel.editor.tests/build.properties
editor/tests/org.fusesource.ide.launcher.tests.integration/build.properties
editor/tests/org.fusesource.ide.launcher.tests/build.properties
editor/tests/org.fusesource.ide.launcher.ui.tests.integration/build.properties
editor/tests/org.fusesource.ide.launcher.ui.tests/build.properties
editor/tests/org.fusesource.ide.project.tests.integration/build.properties
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/build.properties
editor/tests/org.fusesource.ide.projecttemplates.tests/build.properties
jmx/tests/org.fusesource.ide.jmx.camel.tests.integration/build.properties
jmx/tests/org.fusesource.ide.jmx.camel.tests/build.properties
jmx/tests/org.fusesource.ide.jmx.commons.tests/build.properties
jmx/tests/org.fusesource.ide.jmx.diagram.view.tests/build.properties
servers/tests/org.fusesource.ide.server.karaf.core.tests/build.properties
servers/tests/org.fusesource.ide.server.tests/build.properties
site/category.xml
transformation/tests/org.jboss.tools.fuse.transformation.core.tests.integration/build.properties
transformation/tests/org.jboss.tools.fuse.transformation.core.tests/build.properties
transformation/tests/org.jboss.tools.fuse.transformation.editor.tests.integration/build.properties
transformation/tests/org.jboss.tools.fuse.transformation.editor.tests/build.properties

Signed-off-by:...
add sources to update site
Signed-off-by: nickboldt <nboldt@redhat.com>

add sources to update site

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/commands/LayoutCommand.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/custom/GEFLayoutDiagramFeature.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/handler/AutoLayoutAction.java

I think a UI test will be more relevant, what do you think?
This PR can wait for the master to be moved 10.x

Fusetools 2395 fixlayout for edit several jmx routes

---

pom.xml

Update SCM URL project information from fusesource/fuseide to

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/AbstractCamelModelElement.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelModelElementIDUtil.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/model/GlobalNewIdIT.java
core/tests/org.fusesource.ide.camel.model.service.core.tests/src/test/java/org/fusesource/ide/camel/model/service/core/model/CamelModelElementIDUtilTest.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/behaviours/CamelPersistencyBehaviour.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/commands/ImportCamelContextElementsCommand.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/create/ext/CreateFigureFeature.java

- extract in a separated class for ID unicity concerns
- provide more precautions to avoid NPE
- provide test class

FUSETOOLS-2432 - avoid NPE

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/IOUtils.java
core/plugins/org.fusesource.ide.foundation.ui/src/org/fusesource/ide/foundation/ui/archetypes/ArchetypeHelper.java
core/plugins/org.fusesource.ide.imports/src/org/fusesource/ide/imports/sap/IDoc3Archive.java
core/plugins/org.fusesource.ide.imports/src/org/fusesource/ide/imports/sap/JCo3Archive.java
core/plugins/org.fusesource.ide.imports/src/org/fusesource/ide/imports/sap/SAPArchive.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/poller/BaseKarafPoller.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/Karaf2xShutdownController.java

it is fixing "Critical" code smell reported by Sonar

Use try-with-resources

---

core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/CamelIOHandlerIT.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/resources/usingCamelPrefixNamespace-blueprint.xml
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/resources/usingCamelPrefixNamespace-spring.xml

FUSETOOLS-2422 - Add non-regression test when a prefix is used for Camel

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/AbstractCamelModelElement.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelFile.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/GlobalDefinitionCamelModelElement.java
core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/CamelUtils.java
core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/xml/namespace/BlueprintNamespaceHandler.java
core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/xml/namespace/FindCamelNamespaceHandler.java
core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/xml/namespace/SpringNamespaceHandler.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/CamelIOHandlerIT.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/model/GlobalDefinitionsIT.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/resources/externalTagNameCollisionWithCamelTags.xml
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/beans/provider/GlobalBeanContributor.java

merging first this PR https://github.com/jbosstools/jbosstools-fuse/pull/1009 will ease the code review

Fusetools 2422 avoid collision of tag names by respecting namespace

---

Contributing.md

as there is no more catalog generation

FUSETOOLS-2467 - Remove Catalog generation information from Readme

---

core/pom.xml
editor/pom.xml
jmx/pom.xml
servers/pom.xml
targetplatform/pom.xml

Remove groupId and version duplicated from parent pom

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/commands/ImportCamelContextElementsCommand.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/navigator/CamelCtxNavRouteNode.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardRuntimeAndCamelPage.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/CamelProjectConfiguratorIT.java
editor/tests/org.fusesource.ide.projecttemplates.tests/src/test/java/org/fusesource/ide/projecttemplates/util/maven/MavenUtilsTest.java
jmx/tests/org.fusesource.ide.jmx.camel.tests/src/test/java/org/fusesource/ide/jmx/camel/navigator/CamelContextNodeTest.java

Remove unused imports

---

transformation/tests/org.jboss.tools.fuse.transformation.core.tests.integration/src/main/java/org/jboss/tools/fuse/transformation/core/camel/CamelConfigBuilderIT.java

Remove exception not thrown

---

editor/plugins/org.fusesource.ide.branding/src/org/fusesource/ide/branding/wizards/project/WorkingSetGroup.java

Remove unnecessary suppressWarning

---

transformation/tests/org.jboss.tools.fuse.transformation.core.tests.integration/src/main/java/org/jboss/tools/fuse/transformation/core/model/ModelBuilderIT.java
transformation/tests/org.jboss.tools.fuse.transformation.core.tests/src/test/java/example/DeepList.java
transformation/tests/org.jboss.tools.fuse.transformation.core.tests/src/test/java/example/ListsAndNestedTypes.java
transformation/tests/org.jboss.tools.fuse.transformation.core.tests/src/test/java/org/jboss/tools/fuse/transformation/core/dozer/DozerMapperConfigurationTest.java

Suppress Warnings for unused field of test data classes

---

core/plugins/org.fusesource.ide.camel.model.service.impl/pom.xml

Remove duplicated managed version

---

core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/build.properties
core/tests/org.fusesource.ide.camel.model.service.core.tests/build.properties
core/tests/org.fusesource.ide.camel.model.tests.integration/build.properties
core/tests/org.fusesource.ide.camel.tests.util/build.properties
core/tests/org.fusesource.ide.camel.validation.tests.integration/build.properties
core/tests/org.fusesource.ide.camel.validation.tests/build.properties
editor/tests/org.fusesource.ide.camel.editor.tests.integration/build.properties
editor/tests/org.fusesource.ide.camel.editor.tests/build.properties
editor/tests/org.fusesource.ide.launcher.tests.integration/build.properties
editor/tests/org.fusesource.ide.launcher.tests/build.properties
editor/tests/org.fusesource.ide.launcher.ui.tests.integration/build.properties
editor/tests/org.fusesource.ide.launcher.ui.tests/build.properties
editor/tests/org.fusesource.ide.project.tests.integration/build.properties
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/build.properties
editor/tests/org.fusesource.ide.projecttemplates.tests/build.properties
jmx/tests/org.fusesource.ide.jmx.camel.tests.integration/build.properties
jmx/tests/org.fusesource.ide.jmx.camel.tests/build.properties
jmx/tests/org.fusesource.ide.jmx.commons.tests/build.properties
jmx/tests/org.fusesource.ide.jmx.diagram.view.tests/build.properties
servers/tests/org.fusesource.ide.server.karaf.core.tests/build.properties
servers/tests/org.fusesource.ide.server.tests/build.properties
transformation/tests/org.jboss.tools.fuse.transformation.core.tests.integration/build.properties
transformation/tests/org.jboss.tools.fuse.transformation.core.tests/build.properties
transformation/tests/org.jboss.tools.fuse.transformation.editor.tests.integration/build.properties
transformation/tests/org.jboss.tools.fuse.transformation.editor.tests/build.properties

Add missing "/" for directory entry

---

core/plugins/org.fusesource.ide.foundation.ui/src/org/fusesource/ide/foundation/ui/label/ChartLabelProvider.java
core/plugins/org.fusesource.ide.foundation.ui/src/org/fusesource/ide/foundation/ui/util/TextFilters.java
core/plugins/org.fusesource.ide.graph/src/org/fusesource/ide/graph/BigHorizontalShift.java
core/plugins/org.fusesource.ide.graph/src/org/fusesource/ide/graph/DirectedDiagramViewLayoutAlgorithm.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/dialogs/provider/GlobalConfigElementsDialogContentProvider.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/CamelDesignEditorFlyoutPaletteComposite.java
jmx/plugins/org.fusesource.ide.jmx.activemq/src/org/fusesource/ide/jmx/activemq/internal/BrokerFacadeSupport.java
jmx/plugins/org.fusesource.ide.jmx.activemq/src/org/fusesource/ide/jmx/activemq/internal/LocalBrokerFacade.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/Karaf2xStartupLaunchConfigurator.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/OSGiBundleStateController.java

Leverage genericity

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/adopters/creators/UnzipStreamCreator.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/medium/CXfCodeFirstProjectTemplate.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/simple/AMQTemplate.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/simple/CBRTemplate.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/simple/EAPSpringTemplate.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/simple/EmptyProjectTemplate.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/simple/OSESpringBootXMLTemplate.java

Factorize code and use Try-with-resource

---

editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot/.settings/fusetooling/Deploy %%%PLACEHOLDER_PROJECTNAME%%% on OpenShift.launch

for the launch configuration
see https://access.redhat.com/documentation/en-us/red_hat_container_development_kit/3.0/html/getting_started_guide/quickstart-startup#starting-cdk for the defautl values

FUSETOOLS-2383 - Use CDK 3 default values

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/beans/BeanConfigUtil.java

FUSETOOLS-2459 - setting scope by default for new global beans

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/CamelUtils.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/beans/BeanConfigUtil.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/globalconfiguration/beans/BeanConfigUtilIT.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/empty-BlueprintCamelFileWithBothRootAndDeeper.xml
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/empty-BlueprintCamelFileWithDeeperPrefix.xml
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/empty-BlueprintCamelFileWithRootPrefix.xml
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/empty-CamelFileWithBothRootAndDeeper.xml
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/empty-CamelFileWithDeeperPrefix.xml
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/empty-CamelFileWithRootPrefix.xml

FUSETOOLS-2461 - fixing namespacing of new bean node

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/beans/BeanConfigUtil.java

FUSETOOLS-2485 - fixing issue with not creating src/main/java

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/catalog/Parameter.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelComponentUtils.java
core/tests/org.fusesource.ide.camel.model.service.core.tests/src/test/java/org/fusesource/ide/camel/model/service/core/catalog/eips/EipParameterTest.java
core/tests/org.fusesource.ide.camel.model.service.core.tests/testdata/to.json
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/AdvancedEndpointPropertiesSection.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/DetailsSection.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/FusePropertySection.java

review and merge this one first for simplicity reviewing this one https://github.com/jbosstools/jbosstools-fuse/pull/1058

Fusetools 2493 avoid to have space value for enum choice

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/beans/BeanConfigUtil.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/beans/MethodSelectionDialog.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/UIMessages.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/l10n/messages.properties
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/AdvancedBeanPropertiesSection.java

Will update JIRA to include screen shots of design decisions for
discussion.

FUSETOOLS-2454 - initial revisions for method selection dialog

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/eips/GlobalBeanEIP.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/beans/BeanConfigUtil.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/AdvancedBeanPropertiesSection.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/bean/BeanRefAttributeComboFieldPropertyUICreator.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/bean/PropertyRefValidator.java

FUSETOOLS-2453 - adding support for bean references to global beans

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/beans/BeanConfigUtil.java

FUSETOOLS-2511- fix for issue with "factory-method" property on spring

---

editor/plugins/org.fusesource.ide.projecttemplates/META-INF/MANIFEST.MF
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/FuseIntegrationProjectCreatorRunnable.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java

This part helps to get faster for Template creation and seems to have a little effect on stability of the job on CI
i created a separated PR because this one can be merged although the other [one ](https://github.com/jbosstools/jbosstools-fuse/pull/1042) contains a lot of code with patch plugins which would be better to avoid to commit

FUSETOOLS-2132 - deactivate validation during project creation

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtils.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelMavenUtils.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/adopters/configurators/MavenTemplateConfigurator.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/util/ProjectTemplatePatcher.java

FUSETOOLS-2513 - fixed problem with CXF Code First template

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/navigator/CamelCtxNavContentProvider.java

FUSETOOLS-2506 - fix broken expand for context files on Linux

---

editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/amq/simple-fuse-activemq-blueprint/ReadMe.txt
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/amq/simple-fuse-activemq-blueprint/src/main/resources/OSGI-INF/blueprint/camel-blueprint.xml
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/amq/simple-fuse-activemq-spring/src/main/resources/META-INF/spring/camel-context.xml
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForAMQIT.java

Luca's fixes worked beautifully. Tested against both Spring & Blueprint on a Fuse 6.3 server and all is well. Also updated the readme.txt to fix the issue Tomas found.

FUSETOOLS-2405 - amq

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/util/camel/ICamelFacetDataModelProperties.java
servers/plugins/org.fusesource.ide.server.fuse.core/plugin.xml
servers/plugins/org.fusesource.ide.server.karaf.core/plugin.xml

FUSETOOLS-2524 - fix wrong camel facet definition for servers

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtils.java

FUSETOOLS-2447 - fix broken parsing of camel test versions

---

core/tests/org.fusesource.ide.camel.tests.util/src/org/fusesource/ide/camel/test/util/editor/AbstractCamelEditorIT.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelEditor.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/CamelEditorIT.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/routes.xml

FUSETOOLS-2042 - hide Global Config tab for Routes element files

---

core/plugins/org.fusesource.ide.foundation.ui/src/org/fusesource/ide/foundation/ui/properties/NumberPropertyDescriptor.java
jmx/plugins/org.fusesource.ide.jmx.karaf/src/org/fusesource/ide/jmx/karaf/navigator/osgi/CompositeDataPropertySource.java
servers/plugins/org.fusesource.ide.server.karaf.core/OSGI-INF/l10n/bundle.properties
servers/plugins/org.fusesource.ide.server.karaf.core/plugin.xml
servers/plugins/org.fusesource.ide.server.karaf.core/resources/karaf.yaml
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/bean/BaseKarafServerTypeCondition.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/bean/KarafBeanProvider.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/bean/ServerBeanTypeKaraf2x.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/bean/ServerBeanTypeKaraf3x.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/bean/ServerBeanTypeKaraf4x.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/publish/jmx/KarafBundleMBeanPublishBehaviour.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/publish/jmx/KarafBundlesMBeanPublishBehaviour.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/runtime/IKarafRuntime.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/runtime/KarafRuntimeDelegate.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/runtime/KarafRuntimeLocator.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/IKarafServerDelegate.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/Karaf4xServerDelegate.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/KarafServerDelegate.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/Karaf2xStartupLaunchConfigurator.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/Karaf4xStartupLaunchConfigurator.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/util/IKarafToolingConstants.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/util/KarafUtils.java
servers/plugins/org.fusesource.ide.server.karaf.ui/plugin.xml
servers/plugins/org.fusesource.ide.server.karaf.ui/src/org/fusesource/ide/server/karaf/ui/SshConnector.java

FUSETOOLS-2267 - Karaf 4.x server adapter

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/CamelUtils.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/dataformat/wizards/NewDataFormatWizard.java

see https://sonarcloud.io/project/issues?id=fusetools&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL

FUSETOOLS-2186, FUSETOOLS-2486 - remove introduced techincal debt

---

servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/publish/jmx/KarafBundleMBeanPublishBehaviour.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/publish/jmx/KarafBundlesMBeanPublishBehaviour.java

factorize code that has been touched during development of
FUSETOOLS-2267
it was reported by Sonar "leak period" see https://sonarcloud.io/component_measures/metric/new_duplicated_lines_density/list?id=fusetools

FUSETTOLS-2267 - Factorize code

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/preference/ConsolePreferencePage.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/preference/FuseServerRuntimePreferencePage.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/preference/FuseToolingEditorPreferencePage.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/preference/InstalledJREs.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/preference/JBossRuntimeDetection.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/preference/MavenUserSettingsPreferencePage.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/preference/SSH2PreferencePage.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/preference/StagingRepositoriesPreferencePage.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/runtime/ServerBase.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/utils/FuseServerManipulator.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DownloadServerTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/FeaturesServerTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/FeaturesTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/FuseProjectTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/FuseProjectTestLong.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/JMXNavigatorServerTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/JMXNavigatorTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/QuickStartsTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/RegressionFuseTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/RegressionTest.java

https://issues.jboss.org/browse/FUSETOOLS-2550

FUSETOOLS-2550: UI Tests - Preference pages - referencedComposite can't be null

---

core/plugins/org.fusesource.ide.camel.validation/OSGI-INF/l10n/bundle.properties
core/tests/org.fusesource.ide.camel.model.service.core.tests/OSGI-INF/l10n/bundle.properties
core/tests/org.fusesource.ide.camel.tests.util/OSGI-INF/l10n/bundle.properties
core/tests/org.fusesource.ide.camel.validation.tests.integration/OSGI-INF/l10n/bundle.properties
core/tests/org.fusesource.ide.preferences.tests.integration/OSGI-INF/l10n/bundle.properties
editor/tests/org.fusesource.ide.launcher.tests.integration/OSGI-INF/l10n/bundle.properties
editor/tests/org.fusesource.ide.launcher.ui.tests/OSGI-INF/l10n/bundle.properties
editor/tests/org.fusesource.ide.project.tests.integration/OSGI-INF/l10n/bundle.properties
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/OSGI-INF/l10n/bundle.properties
jmx/plugins/org.fusesource.ide.jmx.diagram.view/OSGI-INF/l10n/bundle.properties
jmx/tests/org.fusesource.ide.jmx.camel.tests.integration/OSGI-INF/l10n/bundle.properties
jmx/tests/org.fusesource.ide.jmx.diagram.view.tests/OSGI-INF/l10n/bundle.properties
transformation/plugins/org.jboss.tools.fuse.transformation.editor/OSGI-INF/l10n/bundle.properties
transformation/tests/org.jboss.tools.fuse.transformation.core.tests.integration/OSGI-INF/l10n/bundle.properties
transformation/tests/org.jboss.tools.fuse.transformation.editor.tests.integration/OSGI-INF/l10n/bundle.properties

FUSETOOLS-2541: Update vendor to "JBoss by Red Hat" in all bundles

---

editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/amq/simple-fuse-activemq-spring/ReadMe.txt

FUSETOOLS-2405 - updating spring AMQ template readme

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/pom.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/settings/plugin_customization_with_proxy_settings.ini
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/settings/proxy_settings.xml

FUSETOOLS-2555: Allow specifying proxy for maven artifacts in UI tests

---

servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/l10n/messages.properties

FUSETOOLS-2563 - Improve guidance for workaround error

---

site/pom.xml

Remove usage of property indirection as it triggers errors from enforcer

---

servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/Karaf2xPublishController.java

it is not fixing the issue but try to have more information instead of
NPE

FUSETOOLS-2562 - log information instead of having a NPE

---

core/plugins/org.fusesource.ide.camel.model.service.impl/src/org/fusesource/ide/camel/model/service/internal/CamelService.java

FUSETOOLS-2557 - switch loglevel of catalog fallback logging

---

uitests/plugins/org.jboss.tools.fuse.reddeer/META-INF/MANIFEST.MF
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/utils/FuseServerManipulator.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/FuseModifyModulesPage.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/FuseServerWizard.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DataTransformationDeploymentEAPTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DataTransformationDeploymentTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DeploymentTest.java

https://issues.jboss.org/browse/FUSETOOLS-2550

FUSETOOLS-2550 - UI Tests - Fix broken usage of Preference Pages

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/catalog/cache/CamelCatalogCacheManager.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtils.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelMavenUtils.java
core/plugins/org.fusesource.ide.camel.model.service.impl/.settings/org.eclipse.jdt.core.prefs
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/adopters/AbstractProjectTemplate.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/FuseIntegrationProjectCreatorRunnable.java

recommend to review and merge https://github.com/jbosstools/jbosstools-fuse/pull/1130 before reviewing this one
new result of progress monitor, still not perfect but a bit better
https://drive.google.com/open?id=0B1cUBNButvV9QTQwVHcyOG5TNjQ

FUSETOOLS-2572 - improve progress monitor

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/beans/BeanConfigUtil.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/UIMessages.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/l10n/messages.properties
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/AdvancedBeanPropertiesSection.java

the tests written in https://github.com/jbosstools/jbosstools-fuse/pull/1128 are covering this use case

FUSETOOLS-2569 - Filter void return for Blueprint init method

---

Contributing.md

Provide information to use the Target Platform

---

targetplatform/fuse-jbosstools.target

upgraded versions in the TP target file

---

servers/plugins/org.fusesource.ide.server.fuse.core/src/org/fusesource/ide/server/fuse/core/runtime/FuseESBRuntimeDelegate.java

single equalsIgnoreCase() call.

Replace these toUpperCase()/toLowerCase() and equals() calls with a

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelDesignEditor.java

FUSETOOLS-1835 - non-null check for possible null objects

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtils.java

FUSETOOLS-2584: Allow to specify own configuration for camel2bom.properties

---

core/plugins/org.fusesource.ide.foundation.ui/src/org/fusesource/ide/foundation/ui/properties/BooleanPropertyDescriptor.java
core/plugins/org.fusesource.ide.foundation.ui/src/org/fusesource/ide/foundation/ui/propsrc/BeanTypePropertyMetadata.java
jmx/plugins/org.fusesource.ide.jmx.karaf/src/org/fusesource/ide/jmx/karaf/connection/AbstractKarafJMXConnectionProvider.java
jmx/plugins/org.fusesource.ide.jmx.karaf/src/org/fusesource/ide/jmx/karaf/navigator/osgi/BundlesNode.java
jmx/plugins/org.fusesource.ide.jmx.karaf/src/org/fusesource/ide/jmx/karaf/navigator/osgi/ServicesNode.java
jmx/plugins/org.fusesource.ide.jmx.karaf/src/org/fusesource/ide/jmx/karaf/navigator/osgi/TabularDataHelper.java

during investigation on https://issues.jboss.org/browse/FUSETOOLS-2532

Improve code during investigation

---

core/plugins/org.fusesource.ide.camel.model.service.impl/src/org/fusesource/ide/camel/model/service/internal/CamelService.java
editor/plugins/org.fusesource.ide.branding/src/org/fusesource/ide/branding/wizards/NewCamelXmlWizard.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/custom/CollapseFeature.java
servers/plugins/org.fusesource.ide.server.karaf.ui/src/org/fusesource/ide/server/karaf/ui/runtime/RTIComposite.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/JavaUtil.java

as the variable already holds the assigned value along all execution
paths.

remove useless assignments

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/commands/HighlightNodeCommand.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/utils/StyleUtil.java

- remove non-null check returning always true
- extract methods to reduce cognitive complexity below thresolds and
have clearer code
- extract constant to avoid code duplication

FUSETOOLS-2300 - Improve code during investigation

---

editor/plugins/org.fusesource.ide.branding/src/org/fusesource/ide/branding/wizards/NewCamelTestWizardPageTwo.java

- Reorder the modifiers to comply with the Java Language Specification.
- Use local variable instead for attributes when possible
- use diamond operator for more consise writing

FUSETOOLS-2431 - Improve code during investigation

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/CamelServiceManagerUtil.java
core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/JsonHelper.java
core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/xml/namespace/NamespaceXmlContentDescriberSupport.java
core/tests/org.fusesource.ide.camel.tests.util/src/org/fusesource/ide/camel/tests/util/CommonTestUtils.java
editor/plugins/org.fusesource.ide.branding/src/org/fusesource/ide/branding/wizards/NewCamelTestWizard.java
editor/tests/org.fusesource.ide.launcher.tests.integration/src/main/java/org/fusesource/ide/launcher/tests/integration/remote/debug/ProjectWithDebugAvailableDeployedHelper.java
editor/tests/org.fusesource.ide.launcher.tests.integration/src/main/java/org/fusesource/ide/launcher/tests/integration/remote/debug/RemoteCamelLaunchConfigurationDelegateOverJolokiaIT.java
jmx/plugins/org.fusesource.ide.jmx.commons/src/org/fusesource/ide/jmx/commons/JmxPluginJmxTemplate.java
transformation/plugins/org.jboss.tools.fuse.transformation.core/src/org/jboss/tools/fuse/transformation/core/dozer/DozerMapperConfiguration.java
transformation/plugins/org.jboss.tools.fuse.transformation.core/src/org/jboss/tools/fuse/transformation/core/model/json/JsonModelGenerator.java
transformation/plugins/org.jboss.tools.fuse.transformation.core/src/org/jboss/tools/fuse/transformation/core/model/xml/XmlModelGenerator.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingViewer.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/JavaUtil.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/TestGenerator.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/util/TransformationManager.java

based on Sonar reports.
TODO: investigate how to improve for JMX facade which represents most of
the reported issues

Fix technical debt around exceptions

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelFile.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelRouteContainerElement.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelRouteContainerWithoutGlobalConfigElement.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/CamelIOHandlerIT.java
core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/resources/routeContext.xml
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelEditor.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/CamelEditorCheckOpeningInSpecialCasesIT.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/CamelEditorIT.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/CamelEditorMoveIT.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/basic-routeContext.xml
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/collapseExpand-routeContext.xml
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/delete-routeContext.xml
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/deleteKeepHeight-routeContext.xml
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/insert-routeContext.xml
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/moveInRoute-routeContext.xml
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/reconnect-routeContext.xml
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/reconnect2-routeContext.xml
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/route-routeContext.xml
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/routeContext.xml

FUSETOOLS-2644 - Support routeContext

---

editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot/pom.xml

FUSETOOLS-2674 - Pre-configure FIS template for hot-deploy

---

editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot/pom.xml

FUSETOOLS-2674 - comment springboot-devtool as it seems to cause issue

---

editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/JMXCamelConnectJob.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/actions/ui/SwitchCamelVersionRunnableWithProgress.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/actions/ui/SwitchCamelVersionWizard.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/actions/ui/SwitchCamelVersionWizardPage.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/actions/ui/UnknownTimeMonitorUpdater.java

Use a specific method to end the Thread cleanly instead of calling
interrupt

FUSETOOLS-2659 - Avoid infinite Thread

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/launcher/RedDeer Test.launch

FUSETOOLS-2683: Update RedDeer launch file

---

uitests/plugins/org.jboss.tools.fuse.reddeer/META-INF/MANIFEST.MF
uitests/plugins/org.jboss.tools.fuse.reddeer/plugin.xml
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/CamelExampleConfiguration.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/CamelExampleRequirement.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/CamelExampleRequirementMatcher.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/CamelExampleRunner.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/utils/JarRunner.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/utils/JarRunnerException.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/JMXNavigator.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/JMXNavigatorTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/suite/SmokeTests.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/suite/WithoutServerTests.java

FUSETOOLS-2675: Implement a requirement for Camel examples

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DebuggerTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/LicenseTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/NewFuseProjectWizardTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/RegressionFuseTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/utils/ProjectFactory.java

**recommend to review and merge #1136 before reviewing this one**

UI Tests - Stabilize all tests on one platform

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/pom.xml

FUSETOOLS-2642: Use camel2bom.properties in UI tests

---

targetplatform/fuse-jbosstools.target

updated the target platform to allow build with sources

---

configuration/camel2bom.properties
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtils.java

FUSETOOLS-2682: Add support for Fuse 6.2.1.R9

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/META-INF/MANIFEST.MF
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/utils/LogChecker.java

FUSETOOLS-2671: Add test for collapse/expand feature in Camel Editor

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/FuseProjectTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/FuseProjectTestLong.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/utils/ProjectFactory.java

for more information visit https://issues.jboss.org/browse/FUSETOOLS-2687

FUSETOOLS-2687 - UI Tests - Adjust 'FuseProjectTest' to recent changes

---

CODEOWNERS

introducing CODEOWNERS to automate PR review requests

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtils.java

FUSETOOLS-2680 - Update hardcoded path to github to the master one

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtils.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/FuseBomFilter.java
core/tests/org.fusesource.ide.camel.model.service.core.tests/src/test/java/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtilsTest.java

FUSETOOLS-2691 - FIS bom for Fuse 6 and 7 are the same

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardRuntimeAndCamelPage.java

FUSETOOLS-2712 - remove unused import

---

.github/PULL_REQUEST_TEMPLATE.md

- point to automated part (Sonar/CI PR job build and test result)
- add "avoid duplication" to the checklist

Proposal for improved Github PR template

---

core/tests/org.fusesource.ide.preferences.tests.integration/.classpath
core/tests/org.fusesource.ide.preferences.tests.integration/build.properties

Remove not existing direcoty entry from .classpath and build.properties

---

core/features/org.fusesource.ide.core.feature/feature.properties
editor/features/org.fusesource.ide.camel.editor.feature/feature.properties
editor/plugins/org.fusesource.ide.camel.editor/schema/org.fusesource.ide.editor.dblClickHandler.exsd
editor/plugins/org.fusesource.ide.camel.editor/schema/org.fusesource.ide.editor.globalConfigContributor.exsd
editor/plugins/org.fusesource.ide.camel.editor/schema/org.fusesource.ide.editor.paletteContributor.exsd
editor/plugins/org.fusesource.ide.projecttemplates/schema/org.fusesource.ide.projecttemplates.templates.exsd
jmx/features/org.fusesource.ide.jmx.feature/feature.properties
servers/features/org.fusesource.ide.server.extensions.feature/feature.properties
syndesis/features/org.fusesource.ide.syndesis.extension.feature/feature.properties
transformation/features/org.jboss.tools.fuse.transformation.feature/feature.properties

FUSETOOLS-2734 - Update visible copyrights to 2018

---

syndesis/tests/org.fusesource.ide.syndesis.extension.core.tests/src/test/java/org/fusesource/ide/syndesis/extensions/core/model/SyndesisExtensionUtilInvalidVersionTest.java
syndesis/tests/org.fusesource.ide.syndesis.extension.core.tests/src/test/java/org/fusesource/ide/syndesis/extensions/core/model/SyndesisExtensionUtilValidVersionTest.java

FUSETOOLS-2742 - Use parameterized test to improve readability of cases

---

syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/plugin.xml

FUSETOOLS-2738 - removed duplicated fuse perspective declarations

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/medium/CXfCodeFirstProjectTemplateForFuse7.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java

FUSETOOLS-2741 - ensure template is compatible with the camel version

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/CamelGlobalConfigEditor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/beans/wizards/EditGlobalBeanWizard.java

FUSETOOLS-2433 - fixing issue with not being able to cancel bean edit

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/maven/CamelProjectConfigurator.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForEAPSpringIT.java

FUSETOOLS-2711 - Remove the test sources assembly mapping for war

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/xml/namespace/BlueprintNamespaceHandler.java
core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/xml/namespace/FindCamelNamespaceHandler.java
core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/xml/namespace/FindNamespaceHandlerSupport.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/provider/ActiveMQPaletteEntryDependenciesManager.java
editor/tests/org.fusesource.ide.camel.editor.tests/src/test/java/org/fusesource/ide/camel/editor/provider/ActiveMQPaletteEntryTest.java
editor/tests/org.fusesource.ide.launcher.tests.integration/src/main/java/org/fusesource/ide/launcher/tests/integration/contentype/CamelContentTypeCheckIT.java

FUSETOOLS-2695 - avoid NullPointerException

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardRuntimeAndCamelPage.java

FUSETOOLS-2752 - Fix "next" enablement after "verify" Camel version

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtils.java

FUSETOOLS-2686 - use master branch to retrieve configuration file

---

configuration/ignite.properties
syndesis/plugins/org.fusesource.ide.syndesis.extension.core/src/org/fusesource/ide/syndesis/extensions/core/util/SyndesisExtensionsUtil.java

FUSETOOLS-2772 - upgrade ignite version to 1.2.3

---

core/plugins/org.fusesource.ide.help/.classpath
core/plugins/org.fusesource.ide.help/build.properties

- fix build.properties
- upgrade .classpath to Java 8 accordingly to MANIFEST.MF

Avoid warnings in Help plugin

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/adopters/creators/DSLDependentUnzipStreamCreator.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/medium/AbstractCxfCodeFirstProjectTemplate.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/simple/AMQTemplate.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/simple/AbstractCBRTemplate.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/simple/AbstractEAPSpringTemplate.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/simple/AbstractEmptyProjectTemplate.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/simple/AbstractOSESpringBootXMLTemplate.java

FUSETOOLS-2745 - Factorize code of dsl dependent Template Stream Creator

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelFile.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelComponentUtils.java

- gains 200ms when displaying Advanced tab

FUSETOOLS-2399 - avoid some call to "slow" method

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/navigator/CamelCtxNavContentProvider.java

just avoid NPE as use case to reproduce is not known.

FUSETOOLS-2530 - avoid NPE

---

core/plugins/org.fusesource.ide.imports/src/org/fusesource/ide/imports/sap/SAPToolSuiteImportWizard.java
editor/plugins/org.fusesource.ide.branding/src/org/fusesource/ide/branding/wizards/NewCamelXmlWizard.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/dataformat/wizards/NewDataFormatWizard.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/utils/JobWaiterUtil.java
editor/plugins/org.fusesource.ide.launcher.ui/src/org/fusesource/ide/launcher/ui/launch/ExecutePomActionSupport.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/CamelDebugFacade.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/JMXCamelConnectJob.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/ThreadGarbageCollector.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/actions/ui/SwitchCamelVersionWizard.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/adopters/AbstractProjectTemplate.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/poller/BaseKarafPoller.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/poller/PollThread.java
servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/server/subsystems/OSGiBundleStateController.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/TransformationEditor.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/TransformTestWizardPage.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/wizards/NewTransformationWizard.java

FUSETOOLS-2787 - rework parts catching interruptedexception

---

editor/plugins/org.fusesource.ide.launcher.ui/src/org/fusesource/ide/launcher/ui/Messages.java
editor/plugins/org.fusesource.ide.launcher.ui/src/org/fusesource/ide/launcher/ui/l10n/messages.properties

FUSETOOLS-2725 - removed no more used messages

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/util/BasicProjectCreatorRunnableUtils.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/FuseIntegrationProjectCreatorRunnable.java
syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/wizards/SyndesisExtensionProjectCreatorRunnable.java

FUSETOOLS-2744 - remove use of array for syndesis camel file lookup

---

pom.xml

currently setting --add-modules=ALL-SYSTEM with JDK 9
see comment https://issues.jboss.org/browse/FUSETOOLS-2692?focusedCommentId=13527315&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13527315
this job is executing the tests with JDK 9 (I changed the target branch to build to th ebranch used fo rthis PR) https://fusesource-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Fuse Tooling/job/jbosstools-fuse_master_jdepsTest/6

FUSETOOLS-2692 - Use parent property for JDK module JVM value

---

syndesis/tests/org.fusesource.ide.syndesis.extension.ui.tests.integration/src/main/java/org/fusesource/ide/syndesis/extensions/tests/integration/wizards/SyndesisExtensionProjectCreatorRunnableIT.java

FUSETOOLS-2713 - replaced deprecated maven call in syndesis integration test 

---

servers/plugins/org.fusesource.ide.server.karaf.ui/src/org/fusesource/ide/server/karaf/ui/runtime/v2x/KarafRuntimeFragment.java
servers/tests/org.fusesource.ide.server.karaf.ui.tests/.classpath
servers/tests/org.fusesource.ide.server.karaf.ui.tests/.project
servers/tests/org.fusesource.ide.server.karaf.ui.tests/META-INF/MANIFEST.MF
servers/tests/org.fusesource.ide.server.karaf.ui.tests/OSGI-INF/l10n/bundle.properties
servers/tests/org.fusesource.ide.server.karaf.ui.tests/build.properties
servers/tests/org.fusesource.ide.server.karaf.ui.tests/pom.xml
servers/tests/org.fusesource.ide.server.karaf.ui.tests/src/test/java/org/fusesource/ide/server/karaf/ui/runtime/v2x/KarafRuntimeFragmentTest.java
servers/tests/pom.xml
targetplatform/.settings/org.eclipse.core.resources.prefs

in order to disable "Next" button in the wizard

FUSETOOLS-2575 - Include Home Version warning into error message

---

servers/plugins/org.fusesource.ide.server.karaf.ui/src/org/fusesource/ide/server/karaf/ui/runtime/v2x/KarafRuntimeFragment.java

FUSETOOLS-2807 - remove old workaround code

---

core/plugins/org.fusesource.ide.camel.model.service.core/META-INF/MANIFEST.MF
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtils.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/versionmapper/CamelForFIS20ToBomMapper.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/versionmapper/CamelForFuse6ToBomMapper.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/versionmapper/CamelForFuse7ToBomMapper.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/versionmapper/CamelForWildflyFuse7ToBomMapper.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/versionmapper/FISBomToFabric8MavenPluginMapper.java
core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java
core/tests/org.fusesource.ide.camel.model.service.core.tests/src/test/java/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtilURLMappingFileTest.java
core/tests/org.fusesource.ide.camel.model.service.core.tests/src/test/java/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtilsTest.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/util/ProjectTemplatePatcher.java
syndesis/plugins/org.fusesource.ide.syndesis.extension.core/META-INF/MANIFEST.MF
syndesis/plugins/org.fusesource.ide.syndesis.extension.core/src/org/fusesource/ide/syndesis/extensions/core/util/IgniteVersionMapper.java
syndesis/plugins/org.fusesource.ide.syndesis.extension.core/src/org/fusesource/ide/syndesis/extensions/core/util/SyndesisExtensionsUtil.java

FUSETOOLS-2748 - Factorize code to retrieve online property values

---

editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/CamelDebugFacade.java
editor/tests/org.fusesource.ide.launcher.tests/src/test/java/org/fusesource/ide/launcher/debug/model/CamelDebugFacadeTest.java
jmx/tests/org.fusesource.ide.jmx.camel.tests.integration/src/org/fusesource/ide/jmx/camel/tests/integration/navigator/RemoteDebugWhenEditingRoutesFromJMXNavigatorIT.java

FUSETOOLS-2430 - Support "Edit Routes" in JMX view for multi context

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/maven/CamelProjectConfigurator.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/CamelProjectConfiguratorForOldFuseToolingMetadataIT.java

it is now configured on Maven project added and on dependencies update

FUSETOOLS-2756 - configure Camel project on Maven project added event

---

core/plugins/org.fusesource.ide.camel.validation/src/org/fusesource/ide/camel/validation/model/TextParameterValidator.java
core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithSameComponentIdAndComponentDefinitionId.xml
core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithSameComponentIdAndComponentDefinitionIdAndRegisterEndpointsIdsSetToFalse.xml
core/tests/org.fusesource.ide.camel.validation.tests.integration/resources/routeWithSameComponentIdAndComponentDefinitionIdAndRegisterEndpointsIdsSetToTrue.xml
core/tests/org.fusesource.ide.camel.validation.tests.integration/src/org/fusesource/ide/camel/validation/xml/AbstractXMLCamelRouteValidorTestHelper.java
core/tests/org.fusesource.ide.camel.validation.tests.integration/src/org/fusesource/ide/camel/validation/xml/XMLCamelRoutesValidatorCheckIdIT.java

FUSETOOLS-2394 - adapt validation for Camel 2.20

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/globalconfiguration/beans/BeanConfigUtil.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/UIMessages.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/l10n/messages.properties
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/AdvancedBeanPropertiesSection.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/globalconfiguration/beans/BeanConfigUtilIT.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/globalconfiguration/beans/wizards/BeanEditWizardIT.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/globalconfiguration/beans/wizards/NewBeanWizardIT.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/bean-blueprint/pom.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/bean-blueprint/src/main/java/hello/FactoryBean.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/bean-spring/src/main/java/hello/FactoryBean.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ConfigurationsEditorBeanTest.java

Fusetools 2567 improve filtering of methods available

---

syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/maven/SyndesisExtensionProjectConfigurator.java

I don't know how to reproduce the issue (and so to write an interesting test)

FUSETOOLS-2823 - avoid NPE

---

servers/plugins/org.fusesource.ide.server.karaf.core/src/org/fusesource/ide/server/karaf/core/publish/jmx/KarafBundleMBeanPublishBehaviour.java
servers/tests/org.fusesource.ide.server.karaf.core.tests/src/test/java/org/fusesource/ide/server/karaf/core/publish/jmx/KarafBundleMBeanPublishBehaviourTest.java
servers/tests/org.fusesource.ide.server.karaf.core.tests/src/test/java/org/fusesource/ide/server/karaf/core/publish/jmx/MockedCompositeData.java
servers/tests/org.fusesource.ide.server.karaf.core.tests/src/test/java/org/fusesource/ide/server/karaf/core/publish/jmx/MockedTabularData.java

FUSETOOLS-2827 - Avoid NPE when unresolved bundle has been deployed

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/HttpClient.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/component/AbstractURICamelComponent.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/condition/TableHasRow.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/CamelExampleRunner.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/runtime/impl/ServerAS.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/runtime/impl/ServerKaraf.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/FusePropertiesView.java

such as "StringBuilder".
and fix some other Sonar reported issues on same classes

Replace the synchronized class "StringBuffer" by an unsynchronized one

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/NewFuseIgniteExtensionProjectDependenciesPage.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/NewFuseIgniteExtensionProjectDetailsPage.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/NewFuseIgniteExtensionProjectFirstPage.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/NewFuseIgniteExtensionProjectWizard.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/META-INF/MANIFEST.MF
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/NewFuseIgniteExtWizardTest.java

https://issues.jboss.org/browse/FUSETOOLS-2776

FUSETOOLS-2776 - UI Tests - New "quick" test for "New Fuse Ignite Extension Project" wizard

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/FusePropertiesView.java

Fix value retrieval in Fuse details properties Views Red Deer for ID

---

pom.xml
uitests/plugins/org.jboss.tools.fuse.reddeer/plugin.xml
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/condition/ContextMenuHasItem.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/condition/OpenShiftExplorerLoadingIsCompleted.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/condition/OpenShiftPodIsRunning.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/launchconfigurations/DefaultLaunchConfigurationJRETab.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/launchconfigurations/MavenBuildLaunchConfiguration.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/OpenShiftConfiguration.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/OpenShiftRequirement.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/OpenShiftExplorer.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/OpenShiftExplorerException.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/CreateOpenShiftProjectWizard.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/NewOpenShiftConnectionWizard.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/pom.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/FuseOnOpenShiftTest.java

https://issues.jboss.org/browse/FUSETOOLS-2587

FUSETOOLS-2587 - UI Tests - New test for deployment to OpenShift

---

uitests/plugins/org.jboss.tools.fuse.reddeer/META-INF/MANIFEST.MF
uitests/plugins/org.jboss.tools.fuse.reddeer/plugin.xml
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/CamelCatalogUtils.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/CamelCatalogConfiguration.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/CamelCatalogRequirement.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/PaletteViewExt.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelCatalogDefaultTest.java

FUSETOOLS-2613 - Create structure for using different versions of Camel catalog in tests

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/JMXNavigator.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/Message.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/MessagesView.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/JolokiaManipulationTest.java

FUSETOOLS-2689: UI Tests - Try to manipulate with routes via Jolokia

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/NewFuseIntegrationProjectWizard.java

FUSETOOLS-2847: UI Tests - Fix SupportedCamelVersions test

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/l10n/messages.properties

FUSETOOLS-2872 - updating REST tab preference for read only clarity

---

configuration/igniteVersionToDisplayName.properties

FUSETOOLS-2812 - remove tp3 version from syndesis config file

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java

FUSETOOLS-2846 - update to use master branch for configuration files

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardRuntimeAndCamelPage.java

- use the Observable Value to have the correct up-to-date values
- fix also the validation when using a version which is not part of the
proposed one
I think that the use case is covered by UI tests, to be confirmed by @tsedmik
EDIT: not covered, created https://issues.jboss.org/browse/FUSETOOLS-2890 

FUSETOOLS-2877 - Fix disablement of Camel version drop down

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/RestConfigEditor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/RestModelBuilder.java

FUSETOOLS-2886 - support all rest elements in editor

---

configuration/defaultVersionToSelect.properties
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtils.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/versionmapper/DefaultVersions.java
core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java

FUSETOOLS-2899 - provide online configuration for camel version to

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/projectexplorer/CamelProject.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/pom.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/SingleFuseProjectTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/utils/FuseProjectDefinition.java

https://issues.jboss.org/browse/FUSETOOLS-2901

FUSETOOLS-2901 - New UI test for checking project creation

---

pom.xml
uitests/README.md
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/pom.xml

FUSETOOLS-2697: Execute Fuse UI smoke tests after each PR

---

editor/plugins/org.fusesource.ide.projecttemplates/OSGI-INF/l10n/bundle.properties

FUSETOOLS-2909 - remove question mark at end of Spring Boot template

---

core/plugins/org.fusesource.ide.camel.model.service.impl/META-INF/MANIFEST.MF

FUSETOOLS-2896 - Remove old OSGI Service Component registration

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java

FUSETOOLS-2899 - set back config to master branch

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtils.java
core/tests/org.fusesource.ide.camel.model.service.core.tests/src/test/java/org/fusesource/ide/camel/model/service/core/util/CamelCatalogUtilsTest.java

FUSETOOLS-2907 - Provide more precise Bom Mapping for manually entered

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardRuntimeAndCamelPage.java
syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/wizards/pages/SyndesisExtensionProjectWizardExtensionDetailsPage.java

FUSETOOLS-2840 - fixed wrong validation if verify version is canceled

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/CamelCatalogUtils.java

FUSETOOLS-2806: UI Tests - Extend 'Camel catalog' testing util structure

---

core/plugins/org.fusesource.ide.help/contexts.xml

Signed-off-by: Melissa Flinn <mflinn@redhat.com>

FSUEDOC-2433 fix context.xml file

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/FusePropertySection.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/properties/FusePropertySectionIT.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/JolokiaManipulationTest.java

FUSETOOLS-2341 - provide attribute name instead of generic "Language"

---

core/plugins/org.fusesource.ide.cheatsheets/content/createCamelProject.xml

FUSETOOLS-2908 - Update description of cheatsheet

---

changeEclipse.sh

added script to change eclipse versions

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardRuntimeAndCamelPage.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/filter/KarafRuntimeFilter.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/filter/RuntimeViewerFilter.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/filter/WildflyRuntimeFilter.java
editor/tests/org.fusesource.ide.projecttemplates.tests/src/test/java/org/fusesource/ide/projecttemplates/wizards/pages/filter/KarafRuntimeFilterTest.java
editor/tests/org.fusesource.ide.projecttemplates.tests/src/test/java/org/fusesource/ide/projecttemplates/wizards/pages/filter/WildflyRuntimeFilterTest.java

FUSETOOLS-2879 - Filter Runtime types in drop-down

---

pom.xml

rollback to 4.5 parent pom because new one doesn't work

---

site/category.xml

FUSETOOLS-2922 - adding wsdl2rest integration bundles to site file

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorTest.java

FUSETOOLS-2595: UI Tests - Improve Camel Editor tests with xpath validation on underlayer XML file

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/CamelCatalogUtils.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/CamelEditor.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/FusePropertiesView.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelCatalogComponentsTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelCatalogDefaultTest.java

FUSETOOLS-2804: UI Tests - Create a new 'quick' test for component 'Properties view'

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ProblemsViewTest.java

https://issues.jboss.org/browse/FUSETOOLS-2276

FUSETOOLS-2276 - Fix error with ProblemsViewTest

---

editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForCBRIT.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForCXFCodeFirstIT.java

FUSETOOLS-2963 - deactivate CBR test for Community version > 2.20.0

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/projectexplorer/CamelProject.java

FUSETOOLS-2978 - avoid Widget is disposed when accessing Camel project

---

pom.xml

FUSETOOLS-2951 - remove no more used/invalid repositories from top-level

---

editor/tests/org.fusesource.ide.launcher.tests.integration/src/main/java/org/fusesource/ide/launcher/tests/integration/remote/debug/ProjectWithDebugAvailableDeployedHelper.java

execution
- how to know what interrupted this thread?

FUSETOOLS-2973 - workaround to avoid random failure during test

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java

FUSETOOLS-2956 - switch back online config files to master branch

---

editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/actions/ui/SwitchCamelVersionWizardIT.java

FUSETOOLS-2990 - close wizard dialog at end of test

---

editor/plugins/org.fusesource.ide.wsdl2rest.ui/META-INF/MANIFEST.MF
editor/plugins/org.fusesource.ide.wsdl2rest.ui/OSGI-INF/l10n/bundle.properties
editor/plugins/org.fusesource.ide.wsdl2rest.ui/build.properties
editor/plugins/org.fusesource.ide.wsdl2rest.ui/plugin.xml

-- added wizard description
-- externalized bundle-used strings

FUSETOOLS-3000 - updating wsdl2rest wizard name

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/CamelCatalogUtils.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/MavenDependency.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/projectexplorer/CamelProject.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorDataFormatTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorLanguageTest.java

FUSETOOLS-2606: Create UI test for language / dataformats properties

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/FilteredSelectionDialog.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ConfigurationsEditorBeanTest.java

FUSETOOLS-2612: UI Tests - Beans test checking for initialization of wizard with package name and classname

---

editor/plugins/org.fusesource.ide.wsdl2rest.ui/build.properties

FUSETOOLS-2993 - embed missing icon for wsdl 2 rest wizard

---

editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForCBRIT.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForCXFCodeFirstIT.java

for CBR and CXF code first with Spring for Camel version > 2.20.0

FUSETOOLS-2963 - reactivate tests with Community version

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorAdditionTest.java

FUSETOOLS-2617: UI Tests - extend CamelEditorTest - components creation

---

editor/plugins/org.fusesource.ide.wsdl2rest.ui/src/org/fusesource/ide/wsdl2rest/ui/wizard/Wsdl2RestWizard.java
editor/tests/org.fusesource.ide.wsdl2rest.ui.tests.integration/src/main/java/org/fusesource/ide/wsdl2rest/ui/tests/integration/Wsdl2RestWizardIT.java

-- used approach Aurelien applied in his local repo

FUSETOOLS-2968 - Adding progress monitor

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/rest/RestElementPropertiesSection.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/rest/RestVerbElementPropertiesSection.java
editor/plugins/org.fusesource.ide.wsdl2rest.ui/OSGI-INF/l10n/bundle.properties
editor/plugins/org.fusesource.ide.wsdl2rest.ui/src/org/fusesource/ide/wsdl2rest/ui/internal/i10n/messages.properties

FUSETOOLS-3003 - updating labels/text per docs suggestions

---

editor/plugins/org.fusesource.ide.wsdl2rest.ui/plugin.xml

FUSETOOLS-2943 - make wsdl2rest wizard top level

---

editor/features/org.fusesource.ide.camel.editor.feature/feature.xml

as dependency of the Fuse Tooling editor feature

FUSETOOLS-2948 - Include Camel LSP client

---

editor/tests/org.fusesource.ide.launcher.tests.integration/src/main/java/org/fusesource/ide/launcher/tests/integration/remote/debug/ProjectWithDebugAvailableDeployedHelper.java

rethrow interrupt in catched interruptedexception

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/condition/TreeHasItem.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/CamelDataFormatDialog.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/CamelEndpointDialog.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/ConfigurationsEditor.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ConfigurationsEditorDataFormatTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ConfigurationsEditorEndpointTest.java

…st and ConfigurationsEditorEndpointsTest

FUSETOOLS-2667: UI Tests - Fix test ConfigurationsEditorDataFormatsTest

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelEditor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/RestConfigEditor.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/restconfiguration/RestEditorTestIT.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/resources/rest-camelContext.xml

-- handle case where original selection not found as when a Rest element
or operation was deleted in the Source tab

FUSETOOLS-2980 - reset selection of Rest Element & Rest operation

---

targetplatform/fuse-jbosstools.target

fix TP build

---

syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/connector/simple/pom.xml
syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/step/camelroute/pom.xml
syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/step/javabean/pom.xml

FUSETOOLS-3018 - added Red Hat GA repo to syndesis templates pom.xml

---

syndesis/plugins/org.fusesource.ide.syndesis.extension.core/src/org/fusesource/ide/syndesis/extensions/core/util/SyndesisExtensionsUtil.java
syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/l10n/messages.properties
syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/wizards/pages/SyndesisExtensionProjectWizardExtensionDetailsPage.java
syndesis/tests/org.fusesource.ide.syndesis.extension.core.tests/src/test/java/org/fusesource/ide/syndesis/extensions/core/model/SyndesisExtensionUtilInvalidVersionTest.java
syndesis/tests/org.fusesource.ide.syndesis.extension.core.tests/src/test/java/org/fusesource/ide/syndesis/extensions/core/model/SyndesisExtensionUtilValidVersionTest.java

FUSETOOLS-3013 - added better validation for the Ignite Version field

---

syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/connector/simple/pom.xml
syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/step/camelroute/pom.xml
syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/step/javabean/pom.xml
syndesis/tests/org.fusesource.ide.syndesis.extension.ui.tests.integration/src/main/java/org/fusesource/ide/syndesis/extensions/tests/integration/SyndesisExtensionProjectCreatorRunnableIT.java

FUSETOOLS-3018 - also provide Red Hat GA repo as pluginRepository

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/utils/MavenUtils.java
editor/tests/org.fusesource.ide.camel.editor.tests/src/test/java/org/fusesource/ide/camel/editor/utils/MavenUtilsTest.java

FUSETOOLS-2944 - added checks to prevent NPE in MavenUtils, fixes #1414

---

syndesis/plugins/org.fusesource.ide.syndesis.extension.core/src/org/fusesource/ide/syndesis/extensions/core/util/IgniteVersionMapper.java

update the fallback for Fuse Online version to most recent GA version

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/CamelRestDSLFromWSDLAdvancedPage.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/CamelRestDSLFromWSDLFirstPage.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/CamelRestDSLFromWSDLWizard.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/wsdl2rest/WSDLFileExample.wsdl
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/wsdl2rest/WSDLFileInvalid.wsdl
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelRestDSLFromWSDLWizardTest.java

FUSETOOLS-2992: UI Tests - Create tests for new 'wsdl2rest' wizard

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelContextElement.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/RestConfigurationElement.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/eips/RestConfigurationElementEIP.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/UIMessages.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/internal/l10n/messages.properties
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/RestConfigEditor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/RestConfigUtil.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/actions/AddRestConfigurationAction.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/actions/DeleteRestConfigurationAction.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/actions/RestEditorAction.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/restconfiguration/RestEditorTestIT.java

-- make fields on the REST tab editable for REST
Configuration details
-- enable plus button for adding a new REST Configuration to a file that
doesn't have one
-- enable X button for removing ALL REST Configuration elements & REST
Elements
-- adjusted approach to go with SWT UI hooks instead of data binding
-- added new integration test

FUSETOOLS-3027 - making the REST Configuration details writable

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/rest/RestElementPropertiesSection.java

FUSETOOLS-3029 - enabling Rest Element property page

---

configuration/ReadMe.md
syndesis/plugins/org.fusesource.ide.syndesis.extension.core/OSGI-INF/l10n/bundle.properties
syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/OSGI-INF/l10n/bundle.properties
syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/l10n/messages.properties
syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/wizards/pages/SyndesisExtensionProjectWizardExtensionDetailsPage.java
syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/connector/simple/README.MD
syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/connector/simple/pom.xml
syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/step/camelroute/README.MD
syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/step/camelroute/pom.xml
syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/step/javabean/README.MD
syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/step/javabean/pom.xml

FUSETOOLS-3009 - replace Fuse Ignite with Fuse Online in UI

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/config/deploymentTest-activemq.cfg
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DeploymentTest.java

FUSETOOLS-2958: New UI test - Try to deploy all available templates to a runtime

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ConfigurationsEditorBeanTest.java

FUSETOOLS-2749: Create bot test for canceling out of editing a global bean

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java

FUSETOOLS-3023 - set back online configuration file to master branch

---

editor/tests/org.fusesource.ide.camel.editor.tests.integration/META-INF/MANIFEST.MF
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/META-INF/MANIFEST.MF

FUSETOOLS-3023 - update plugin version in integration test

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/wizards/pages/FuseIntegrationProjectWizardRuntimeAndCamelPage.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/NewFuseProjectVerifyBTNTest.java

FUSETOOLS-3052 - Support typing "displayed name" of camel version

---

editor/plugins/org.fusesource.ide.wsdl2rest/pom.xml
editor/tests/org.fusesource.ide.camel.editor.tests.integration/META-INF/MANIFEST.MF
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/META-INF/MANIFEST.MF

Fusetools 2966 upgrade wsdl2 rest

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/RestConfigEditor.java

- fixed for REST element list
- added scrollable section for REST operations list

FUSETOOLS-2898 - addressing scroll bars

---

editor/plugins/org.fusesource.ide.camel.editor/META-INF/MANIFEST.MF
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/RestConfigEditor.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/actions/AddRestConfigurationAction.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/actions/AddRestElementAction.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/actions/AddRestOperationAction.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/actions/DeleteRestConfigurationAction.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/actions/DeleteRestElementAction.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/actions/DeleteRestOperationAction.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/actions/RestEditorAction.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/restconfiguration/RestEditorTestIT.java

FUSETOOLS-3046 - some refactoring clean-up

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/CamelEditor.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/SourceEditor.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelLSPCompletionTest.java

FUSETOOLS-3006: Prepare UI tests for Apache Camel Tooling (LSP)

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/RESTEditor.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/AddRESTOperationWizard.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/RESTEditorAdvancedTest.java

FUSETOOLS-3042: UI Tests - Create tests for REST page (editable mode)

---

editor/plugins/org.fusesource.ide.launcher/META-INF/MANIFEST.MF
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/launching/CamelSourceLookupDirector.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/launching/CamelSourceLookupParticipant.java
editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/launching/CamelSourcePathComputerDelegate.java

FUSETOOLS-3058 - code cleaning during investigation

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/CamelUtils.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/TransformationEditor.java
transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/CloseEditorWithoutValidTransformationEditorInput.java

Fusetools 3057 clean code during investigation

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/CamelEditor.java

FUSETOOLS-3060 - fix issue with persisting rest editor changes

---

editor/plugins/org.fusesource.ide.wsdl2rest/pom.xml

FUSETOOLS-2945 - updating wsdl2rest version to get ID generation

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/condition/ContextMenuHasItem.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/OpenShiftExplorer.java

https://issues.jboss.org/browse/FUSETOOLS-3070

FUSETOOLS-3070 - Fix 'FuseOnOpenShiftTest'

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java

FUSETOOLS-3022 : switch back to master branch for configuration files

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/DocumentationSection.java

FUSETOOLS-3004 - fixing rest DSL context ID from help

---

targetplatform/fuse-jbosstools.target

updated target platform to latest versions

---

servers/plugins/org.fusesource.ide.server.fuse.core/OSGI-INF/l10n/bundle.properties

FUSETOOLS-3019 - rename server adapter from 7.0 to 7+

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java

FUSETOOLS-3074 - switch back config to master branch

---

editor/plugins/org.fusesource.ide.wsdl2rest/pom.xml

FUSETOOLS-2945 - use 7.1 GA version for wsdl2rest libraries

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelContextElement.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/RestConfigEditor.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/restconfiguration/RestEditorTestIT.java

FUSETOOLS-3088 - fix issues when IDs on Rest Elements are changed

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/properties/DocumentationSection.java

-- new context-ids will be enabled with content with upcoming help
update

FUSETOOLS-2462 - integrating Context help on Global Config page

---

editor/plugins/org.fusesource.ide.wsdl2rest.ui/src/org/fusesource/ide/wsdl2rest/ui/wizard/pages/Wsdl2RestWizardSecondPage.java

Fusetools 2997 fix destination camel foldr button

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java

FUSETOOLS-3095 - Switch back to master config branch

---

core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/resources/dummySpringPom.xml

FUSETOOLS-3163 - adding spring dependency to FuseProject default pom

---

editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/component/wizard/ComponentManager.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/AddComponentDependencyRunnable.java
editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/restconfiguration/RestConfigEditor.java
editor/plugins/org.fusesource.ide.wsdl2rest.ui/src/org/fusesource/ide/wsdl2rest/ui/wizard/Wsdl2RestWizard.java
editor/plugins/org.fusesource.ide.wsdl2rest/pom.xml
editor/tests/org.fusesource.ide.camel.editor.tests/src/test/java/org/fusesource/ide/camel/editor/component/wizard/ComponentManagerTest.java
editor/tests/org.fusesource.ide.wsdl2rest.ui.tests.integration/META-INF/MANIFEST.MF
editor/tests/org.fusesource.ide.wsdl2rest.ui.tests.integration/src/main/java/org/fusesource/ide/wsdl2rest/ui/tests/integration/Wsdl2RestWizardIT.java

FUSETOOLS-2869 - adding more dependencies via wsdl2rest wizard

---

editor/plugins/org.fusesource.ide.launcher.ui/META-INF/MANIFEST.MF
editor/plugins/org.fusesource.ide.launcher.ui/src/org/fusesource/ide/launcher/ui/propertytester/CamelLocalLaunchPropertyTester.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java

Fusetools 3169 run as debug as local camel fornew fuse bom

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/CamelRestDSLFromWSDLAdvancedPage.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelRestDSLFromWSDLWizardTest.java

FUSETOOLS-3156: Provide Ui test covering usecase in FUSETOOLS-2997

---

core/plugins/org.fusesource.ide.camel.model.service.impl.v2210fuse710018redhat00001/.project
tools/m2-repo-cleaner/.project

FUSETOOLS-3176 - remove useless project natures

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ConfigurationsEditorBeanTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/RESTEditorAdvancedTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/RESTEditorTest.java

FUSETOOLS-3157: UI Tests - Improve stability and clean up of obsolete code

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/simple/AMQTemplate.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/simple/CBRTemplateForFuse6.java
editor/tests/org.fusesource.ide.projecttemplates.tests/src/test/java/org/fusesource/ide/projecttemplates/impl/simple/AMQTemplateTest.java
editor/tests/org.fusesource.ide.projecttemplates.tests/src/test/java/org/fusesource/ide/projecttemplates/impl/simple/CBRTemplateForFuse6Test.java

FUSETOOLS-3085 - Restrict CBR and AMQ Template to 6.2 or 6.3R9+

---

configuration/ReadMe.md

Lhein fusetools 3170 improvereadme

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java

FUSETOOLS-3170 - Switch back config to master branch

---

editor/plugins/org.fusesource.ide.project/META-INF/MANIFEST.MF

when a new version without regression will be available, we will just
need to move to this new version
https://issues.jboss.org/browse/JBIDE-26563 needs to be fixed before this PR can build (and so be merged)

FUSETOOLS-3185 - Avoid 0.9.0 which is introducing regression

---

editor/tests/org.fusesource.ide.launcher.tests.integration/src/main/resources/camel-context.xml
editor/tests/org.fusesource.ide.launcher.tests.integration/src/main/resources/jmx-pom.xml

FUSETOOLS-3191 - have internal project used for test java 11 compatible

---

pom.xml

Update Jacoco maven plugin to version 0.8.3

---

core/tests/org.fusesource.ide.camel.tests.util/src/org/fusesource/ide/camel/tests/util/AbstractProjectCreatorRunnableIT.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java
syndesis/tests/org.fusesource.ide.syndesis.extension.ui.tests.integration/src/main/java/org/fusesource/ide/syndesis/extensions/tests/integration/SyndesisExtensionProjectCreatorRunnableIT.java

FUSETOOLS-3200 - ignore jdk 11 warning

---

core/tests/org.fusesource.ide.camel.tests.util/META-INF/MANIFEST.MF
core/tests/org.fusesource.ide.camel.tests.util/src/org/fusesource/ide/camel/tests/util/AbstractProjectCreatorRunnableIT.java
core/tests/org.fusesource.ide.camel.tests.util/src/org/fusesource/ide/camel/tests/util/JDKInstaller.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java
syndesis/tests/org.fusesource.ide.syndesis.extension.ui.tests.integration/src/main/java/org/fusesource/ide/syndesis/extensions/tests/integration/SyndesisExtensionProjectCreatorRunnableIT.java

FUSETOOLS-3198 - use JDK 8 as installed JRE for templates tests

---

editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/eap-wildfly/camel-test-cdi/pom.xml
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/eap-wildfly/camel-test-spring-fuse6/pom.xml
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/eap-wildfly/camel-test-spring-fuse7.1/pom.xml
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/eap-wildfly/camel-test-spring-fuse7/pom.xml
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/eap-wildfly/camel-test-spring-fusefis/pom.xml
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/eap-wildfly/medium-fuse-eap/pom.xml

to be reviewed first https://github.com/jbosstools/jbosstools-fuse/pull/1519

Fusetools 3207 workaround for java12

---

Build.md
Contributing.md
ReadMe.md
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/eap-wildfly/camel-test-cdi/README.md
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/eap-wildfly/camel-test-spring-fuse6/README.md
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/eap-wildfly/camel-test-spring-fuse7.1/README.md
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/eap-wildfly/camel-test-spring-fuse7/README.md
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/eap-wildfly/camel-test-spring-fusefis/README.md
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/eap-wildfly/medium-fuse-eap/README.md
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/cbr/simple-fuse-cbr-blueprint-fuse6/README.md
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/cbr/simple-fuse-cbr-blueprint-fuse7.1/README.md
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/cbr/simple-fuse-cbr-blueprint-fuse7/README.md
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/cbr/simple-fuse-cbr-spring-fuse6/README.md
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/cbr/simple-fuse-cbr-spring-fuse7.1/README.md
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/cbr/simple-fuse-cbr-spring-fuse7/README.md
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot-fuse6/README.md
uitests/README.md

FUSETOOLS-3222 - use http instead of https for url referenced in

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java

FUSETOOLS-3183 - switch back to master for config

---

syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/src/org/fusesource/ide/syndesis/extensions/ui/maven/SyndesisExtensionProjectConfigurator.java
syndesis/tests/org.fusesource.ide.syndesis.extension.ui.tests.integration/META-INF/MANIFEST.MF
syndesis/tests/org.fusesource.ide.syndesis.extension.ui.tests.integration/src/main/java/org/fusesource/ide/syndesis/extensions/tests/integration/SyndesisProjectConfiguratorIT.java

FUSETOOLS-3054 - avoid false detection of Camel nature

---

core/plugins/org.fusesource.ide.camel.model.service.core/build.properties
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/internal/Trace.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelFilesFinder.java

FUSETOOLS-3186 - provide possibility to trace time spent to search if

---

pom.xml
targetplatform/fuse-jbosstools.target
targetplatform/pom.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/pom.xml

FUSETOOLS-3222 - replace http url by https one

---

servers/plugins/org.fusesource.ide.server.karaf.ui/src/org/fusesource/ide/server/karaf/ui/runtime/v2x/KarafRuntimeFragment.java

FUSETOOLS-3217 - avoid potential NPE in Karaf Runtime wizard

---

core/tests/org.fusesource.ide.camel.tests.util/src/org/fusesource/ide/camel/tests/util/AbstractProjectCreatorRunnableIT.java
core/tests/org.fusesource.ide.camel.tests.util/src/org/fusesource/ide/camel/tests/util/InstalledJREUtils.java
editor/plugins/org.fusesource.ide.projecttemplates/META-INF/MANIFEST.MF
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/adopters/AbstractProjectTemplate.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/internal/Messages.java
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/l10n/messages.properties
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/util/BasicProjectCreatorRunnable.java
uitests/plugins/org.jboss.tools.fuse.reddeer/META-INF/MANIFEST.MF
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/utils/ProjectFactory.java

to be reviewed first: https://github.com/jbosstools/jbosstools-fuse/pull/1519

FUSETOOLS-3209 - provide warning when jdk11 used on templates not supported

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/ProjectClasspathChangedListener.java

do initialization of projects asynchronously

FUSETOOLS-3232 - Avoid time spent in CamelModelServiceActivator

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/catalog/components/Component.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/catalog/dataformats/DataFormat.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/catalog/eips/Eip.java
core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/catalog/languages/Language.java

FUSETOOLS-3186 - Use cached JSON ObjectReader

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/util/CamelFilesFinder.java

filter for xml files
it is trying to synchronize too many things for our case. it is faster
to reparse the file and check the content ourself

FUSETOOLS-3186 - avoid usage of slow IFile.getContentDescription and

---

Contributing.md

FUSETOOLS-3186 - provide information to do a profiling on a built

---

Contributing.md

FUSETOOLS-3186 use backtick to avoid Github to interpret the *xxx*

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/pom.xml

FUSETOOLS-3233: UI Tests failing due to missing fuse tooling plugin dependencies

---

editor/plugins/org.fusesource.ide.wsdl2rest.ui/.classpath
editor/plugins/org.fusesource.ide.wsdl2rest.ui/META-INF/MANIFEST.MF
editor/plugins/org.fusesource.ide.wsdl2rest.ui/build.properties
editor/plugins/org.fusesource.ide.wsdl2rest.ui/pom.xml
editor/tests/org.fusesource.ide.wsdl2rest.ui.tests.integration/.classpath

FUSETOOLS-3164 - updating to Fuse 7.3 versions of wsdl2rest

---

editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot-fuse7.1/pom.xml
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot-fuse7.1/src/main/resources/application.properties

it ensures to have the version syncrhonized with the used bom

FUSETOOLS-3238 - Use repackaged SpringBoot Maven plugin

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java

FUSETOOLS-3227 - set back to master

---

jmx/tests/org.fusesource.ide.jmx.camel.tests.integration/src/org/fusesource/ide/jmx/camel/tests/integration/navigator/JMXNodesIT.java

FUSETOOLS-3244 - ignore JMXNodesIT to unblock release

---

uitests/plugins/org.jboss.tools.fuse.reddeer/META-INF/MANIFEST.MF
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/preference/InstalledJREs.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/utils/ProjectFactory.java

FUSETOOLS-3231: UI Tests - Make tests independent of 'org.fusesource' dependencies

---

editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/actions/ChangeCamelVersionJob.java
editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/CamelEditorMoveIT.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/actions/SwitchCamelVersionIT.java

FUSETOOLS-3252 - fix typos introducing in previous PR

---

editor/tests/org.fusesource.ide.launcher.tests.integration/src/main/java/org/fusesource/ide/launcher/tests/integration/remote/debug/AbstractRemoteCamelLaunchConfigurationDelegate.java
editor/tests/org.fusesource.ide.launcher.tests.integration/src/main/java/org/fusesource/ide/launcher/tests/integration/remote/debug/ProjectWithDebugAvailableDeployedHelper.java
jmx/tests/org.fusesource.ide.jmx.camel.tests.integration/src/org/fusesource/ide/jmx/camel/tests/integration/navigator/JMXNodesIT.java

FUSETOOLS-3255 - factorize code to always switch to debug perspective

---

core/plugins/org.fusesource.ide.camel.model.service.core/src/org/fusesource/ide/camel/model/service/core/model/CamelContextElement.java

element it goes after the Rest Configuration node.
- tested in the case with no route, elements added correctly
- tested in the case with an existing route, elements added correctly

FUSETOOLS-3245 - ensuring that we always insert a new rest

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java

FUSETOOLS-3257 - switch back to master for configuraion files

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/pom.xml

FUSETOOLS-3263 - Adjust UI tests execution for CodeReady Studio 12.x

---

editor/plugins/org.fusesource.ide.launcher/src/org/fusesource/ide/launcher/debug/model/CamelDebugTarget.java

FUSETOOLS-3266 - avoid potential NPE #1565

---

syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/connector/simple/pom.xml
syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/step/camelroute/pom.xml
syndesis/plugins/org.fusesource.ide.syndesis.extension.ui/template-sources/step/javabean/pom.xml

FUSETOOLS-3269 - Improve error message when incompatible Maven used with

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java

FUSETOOLS-3277 - change back the source uri for the configuration files

---

configuration/igniteVersionToDisplayName.properties
core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java
syndesis/plugins/org.fusesource.ide.syndesis.extension.core/src/org/fusesource/ide/syndesis/extensions/core/util/IgniteVersionMapper.java

FUSETOOLS-3268 - add all Syndesis Fuse version

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java

FUSETOOLS-3268 - set back branch to master

---

targetplatform/fuse-jbosstools.target

openshift.io feature has been removed after openshift.io shutdown

Update Target Platform - remove openshift.io feature

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DeploymentTest.java

FUSETOOLS-3078: Fix 'fuse-deployment' job

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/JMXNavigator.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/RouteManipulationServerTest.java

FUSETOOLS-3272: Fix JMXNavigatorTreeItem matcher

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/NewFuseIgniteProjectTest.java

FUSETOOLS-3271: Fix 'NewFuseIgniteProjectTest vol.2'

FUSETOOLS-3271: Fix 'NewFuseIgniteTest'

---

editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/amq/simple-fuse-activemq-blueprint/pom.xml
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/amq/simple-fuse-activemq-spring/pom.xml

FUSETOOLS2-11 - Replace maven repository access from http to https

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java

FUSETOOLS-3282 - set back branch to master

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/component/IMAPS.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/component/Netty4HTTP.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/component/NettyHTTP.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/component/SNMP.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/component/Servlet.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/utils/ProjectFactory.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorRoutesTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ComponentTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ProblemsViewTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ProjectLocalRunTest.java

FUSETOOLS-3300: Fix UI Smoke tests for interop testing

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/OpenShiftRequirement.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/FuseOnOpenShiftTest.java

FUSETOOLS-3312 - Fix 'FuseOnOpenShiftTest'

---

editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/CamelEditorCheckOpeningInSpecialCasesIT.java

FUSETOOLS-3326 - temporary skip of 2 tests requiring an upgrade on CI

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java

FUSETOOLS-3339 - switch back config to master branch

---

editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/integration/CamelEditorCheckOpeningInSpecialCasesIT.java

FUSETOOLS-3331 - reactivate tests as webkit 2 is now availabel on CI

---

transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/MappingViewer.java

without having interacted with it

FUSETOOLS-3318 - avoid NPE when closing data transformation editor

---

core/tests/pom.xml
editor/tests/pom.xml
jmx/tests/pom.xml
servers/tests/pom.xml
transformation/tests/pom.xml

Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

JBIDE-27320 Remove JRE7 variable from POM

---

editor/plugins/org.fusesource.ide.wsdl2rest.ui/pom.xml

ENTESB-14185 - upgrade wsdl2rest dependency

---

editor/plugins/org.fusesource.ide.wsdl2rest.ui/pom.xml

Use commons-validator 1.7 thus by transitivity commons-beanutils 1.9.4
Signed-off-by: Jeff MAURY <jmaury@redhat.com>

FUSETOOLS-3361: org.fusesource.ide.wsdl2rest.ui uses beanutils 1.9.2

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java

FUSETOOLS-3353 - switch back configuration to master branch

---

core/plugins/org.fusesource.ide.foundation.core/src/org/fusesource/ide/foundation/core/util/OnlineVersionMapper.java

FUSETOOLS-3387 - Switch back config to master branch

---

pom.xml

remove ASF snapshot repo from pom.xml

---

core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/FuseProject.java

The m2e registry is updated asynchronously.
When deleting a project, and recreating one with same name just after,
it can cause StaleMutableRegistryException.
Awaiting that the m2e registry is updated with project removal avoids
this issue.

FUSETOOLS-3309 - workaround for StaleMutableRegistryException

---

core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/util/CamelMavenUtilsTestIT.java

FUSETOOLS2-979 - use specific name for test project for each tests

---

jmx/tests/org.fusesource.ide.jmx.camel.tests.integration/src/org/fusesource/ide/jmx/camel/tests/integration/navigator/JMXNodesIT.java
jmx/tests/org.fusesource.ide.jmx.camel.tests.integration/src/org/fusesource/ide/jmx/camel/tests/integration/navigator/RemoteDebugWhenEditingRoutesFromJMXNavigatorIT.java

to try to spot from where the flakiness is coming on new CI

FUSETOOLS2-981 - provide more precise check in test

---

pom.xml
transformation/plugins/org.jboss.tools.fuse.transformation.core/.classpath
transformation/plugins/org.jboss.tools.fuse.transformation.core/META-INF/MANIFEST.MF
transformation/plugins/org.jboss.tools.fuse.transformation.core/build.properties

JBDS-4912 - upgrade xmlbeans to 4.0.0

---

editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/navigator/CamelCtxNavContentProviderIT.java

on Ci, it seems that the window sometimes lost focus. There should be
another application that is opened, taking the screenshot should allow
to determine what is it and help continuing investigation

FUSETOOLS2-991 - take screenshot on failure

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/projectexplorer/CamelProject.java

archived
previously, it was generated inside the project under test. This project
is deleted at the end of the test and so we do not have access to the
hs_err_pid. Moving it a bit upper in the folder hierarchy will keep it.
@djelinek i'm not a fan of this solution but the easiest to implement. it would be nice if we can have a more common place to put that code. Or if we can provide parameters to tell where to generate the file directly. Any ideas?

FUSETOOLS2-980 - put hs_err_pid files generated in a place that can be

---

core/tests/org.fusesource.ide.camel.model.service.core.tests.integration/src/main/java/org/fusesource/ide/camel/model/service/core/tests/integration/core/io/FuseProject.java

- catch StaleMutableProjectRegistryException and reattempt at the place
which seems the most probable that it is happening.
- usage of both sysout and logger, it seems that because it is inside a
Rule, when launching a Junit plugin test in Eclipse, the bundle is not
started yet

FUSETOOLS-3309 - provide more traces to catch StaleMutableProjectRegistryException root cause

---

core/plugins/org.fusesource.ide.preferences/src/org/fusesource/ide/preferences/initializer/PreferencesInitializer.java

FUSETOOLS2-978 - fix PreferencesInitializer to access via UI Thread

---

editor/tests/org.fusesource.ide.camel.editor.tests.integration/src/main/java/org/fusesource/ide/camel/editor/navigator/CamelCtxNavContentProviderIT.java

randomly on CI, there is sometimes no active shell.

FUSETOOLS2-991 - use first available shell if no active available

---

.github/workflows/build_test.yml
.github/workflows/publish_reports.yml

to see the github actions working, need to look to my fork https://github.com/apupier/jbosstools-fuse/pull/12

FUSETOOLS-3465 - provide github action for basic PR job

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/camel-context-all.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/camel-context-cbr.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/camel-context-otherwise.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/camel-context-routeContextId.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/camel-context.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/bean-blueprint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/bean-spring/src/main/resources/META-INF/spring/camel-context.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-blueprint/src/main/resources/OSGI-INF/blueprint/blueprint.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-spring/src/main/resources/META-INF/spring/camel-context.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/rest-springboot/src/main/resources/META-INF/spring/camel-context.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/test-route-manipulation/src/main/resources/OSGI-INF/blueprint/blueprint.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/routeContextSupportCamelContext.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/routeContextSupportRouteContext.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/routeWithValidationErrorOnGlobalElements.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/routeWithValidationFixedOnGlobalElements.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelLSPCompletionTest.java

requires https://github.com/jbosstools/jbosstools-fuse/pull/1695

Fusetools 3478 reactivate test and provide specific camel xsd version for test resources

---

editor/plugins/org.fusesource.ide.wsdl2rest.ui/.classpath
editor/plugins/org.fusesource.ide.wsdl2rest.ui/pom.xml

FUSETOOLS-3472 - upgrade wsdl2rest.ui plugin for Fuse 7.9

---

editor/plugins/org.fusesource.ide.projecttemplates/plugin.xml
editor/plugins/org.fusesource.ide.projecttemplates/pom.xml
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/simple/OSESpringBootXMLTemplateForFuse79.java
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot-fuse7.9/.settings/fusetooling/Deploy %%%PLACEHOLDER_PROJECTNAME%%% on OpenShift.launch
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot-fuse7.9/LICENSE.md
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot-fuse7.9/README.md
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot-fuse7.9/configuration/settings.xml
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot-fuse7.9/pom.xml
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot-fuse7.9/src/main/java/org/mycompany/Application.java
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot-fuse7.9/src/main/jkube/deployment.yml
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot-fuse7.9/src/main/resources/application.properties
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot-fuse7.9/src/main/resources/logback.xml
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/simple/ose/simple-ose-log-springboot-fuse7.9/src/main/resources/spring/camel-context.xml
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForOSESringBootIT.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableIT.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/pages/model/TemplateModelIT.java
editor/tests/org.fusesource.ide.projecttemplates.tests/src/test/java/org/fusesource/ide/projecttemplates/impl/simple/OSESpringBootXMLTemplateForFuse79Test.java

first iteration with current state before release.
had to redo from
https://github.com/fabric8-quickstarts/spring-boot-camel-xml/tree/fuse-7.x.sb2.redhat
then notable changes:
- replaced registry.redhat.io by registry.access;redhat.com to avoid
need of another login/regsitration
- converted the readme.adoc to readme.md because Jboss Tools is not
coming with a AsciiDoc viewer by default.
- use of a profile "openshift" in launch configuration
for testing before release this is hell, you need to:
* provide the correct camel version manually in wizard
* update manually the
maven versions by finding a working version for
https://repository.jboss.org/nexus/content/groups/ea/org/jboss/redhat-fuse/fuse-springboot-bom/
, https://repository.jboss.org/nexus/content/groups/ea/org/jboss/redhat-fuse/ope …

FUSETOOLS-3460 - provide Fuse on OpenShift template for 7.9

---

editor/plugins/org.fusesource.ide.projecttemplates/plugin.xml
editor/plugins/org.fusesource.ide.projecttemplates/pom.xml
editor/plugins/org.fusesource.ide.projecttemplates/src/org/fusesource/ide/projecttemplates/impl/simple/EAPSpringTemplateForFuse79.java
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/eap-wildfly/camel-test-spring-fuse7.8/pom.xml
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/eap-wildfly/camel-test-spring-fuse7.9/README.md
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/eap-wildfly/camel-test-spring-fuse7.9/configuration/settings.xml
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/eap-wildfly/camel-test-spring-fuse7.9/pom.xml
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/eap-wildfly/camel-test-spring-fuse7.9/src/main/java/org/wildfly/camel/examples/cdi/SimpleServlet.java
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/eap-wildfly/camel-test-spring-fuse7.9/src/main/java/org/wildfly/camel/examples/cdi/SomeBean.java
editor/plugins/org.fusesource.ide.projecttemplates/template-sources/medium/eap-wildfly/camel-test-spring-fuse7.9/src/main/webapp/WEB-INF/camel-context.xml
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/FuseIntegrationProjectCreatorRunnableForEAPSpringIT.java
editor/tests/org.fusesource.ide.projecttemplates.tests.integration/src/main/java/org/fusesource/ide/projecttemplates/tests/integration/wizards/pages/model/TemplateModelIT.java
editor/tests/org.fusesource.ide.projecttemplates.tests/src/test/java/org/fusesource/ide/projecttemplates/impl/simple/EAPSpringTemplateForFuse79Test.java

Fusetools2 3384 eap java11 compatible example

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/utils/ProjectFactory.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DebuggingInEditRoutesModeTest.java

Signed-off-by: Filip Pospisil <fpospisi@redhat.com>

FUSETOOLS-2638: UI Tests - Add test for debugging in Edit Routes mode

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/condition/HyperLinkHasText.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/CheatSheetsView.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/CheatSheetsWizard.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CheatSheetsTest.java

Signed-off-by: Filip Pospisil <fpospisi@redhat.com>

FUSETOOLS-2590: UI Tests - Add tests for cheat sheets

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/JMXNavigatorTest.java

FUSETOOLS-3525: Convert fixed UI Test 'JMXNavigatorTest' into master

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/NewFuseIgniteExtWizardTest.java

FUSETOOLS-3529: Fix and convert fixed UI Test 'NewFuseIgniteExtWizardTest' into master branch

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/NewFuseProjectWizardTest.java

FUSETOOLS-3532: Fix and convert fixed UI Test 'NewFuseProjectWizardTest' into master branch

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/NewFuseProjectVerifyBTNTest.java

FUSETOOLS-3531: Fix and convert fixed UI Test 'NewFuseProjectVerifyBTNTest' into master branch

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DefaultTest.java

FUSETOOLS-3521: Convert fixed UI Test 'DefaultTest' into master branch

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/OpenShiftRequirement.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/OpenShiftExplorer.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/NewOpenShiftConnectionWizard.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/FuseOnOpenShiftTest.java

Signed-off-by: Filip Pospisil <fpospisi@redhat.com>

FUSETOOLS-3401: UI Tests - Fix broken 'fuse-openshift' Jenkins job

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorTest.java

FUSETOOLS-3491: UI Tests - Fix LSP UI tests flakiness in CamelEditorTest

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DownloadServerTest.java

FUSETOOLS-2589: UI Tests - Extend 'DownloadServerTest'

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CheatSheetsTest.java

FUSETOOLS-3565: UI Tests - fix 'CheatSheetsTest' issue related to JDK11

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/ProjectTemplate.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/SupportedCamelVersions.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/utils/JDKCheck.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/utils/JDKTemplateCompatibleChecker.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/utils/ProjectFactory.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DataTransformationDefaultTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/NewFuseProjectWizardTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/SingleFuseProjectTest.java

FUSETOOLS-3566: Fix Project Factory JDK11 failures

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/utils/JDKTemplateCompatibleChecker.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/utils/ProjectFactory.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/utils/TransformationDragAndDropManager.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/CamelRestDSLFromWSDLWizard.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorAdditionTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorDataFormatTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelRestDSLFromWSDLWizardTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ComponentTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ConfigurationsEditorDataFormatTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ConfigurationsEditorEndpointTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DataTransformationDefaultTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DataTransformationDeploymentTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DebuggerTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DeploymentTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/FuseOnOpenShiftTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/NewFuseIgniteProjectTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/NewFuseProjectWizardTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/RESTEditorAdvancedTest.java

FUSETOOLS-3600: UI Tests - Fix tests to allow 4.21.3.Final/12.21.3.GA release testing

---

editor/tests/org.fusesource.ide.camel.editor.tests/src/test/java/org/fusesource/ide/camel/editor/GoToMarkerForCamelEditorTest.java
editor/tests/org.fusesource.ide.launcher.ui.tests/src/test/java/org/fusesource/ide/launcher/ui/launch/ExecutePomActionSupportTest.java
pom.xml

Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

bump up to parent pom version = 4.24.0.Final-SNAPSHOT

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/Activator.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/CamelCatalogUtils.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/CamelExampleConfiguration.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/CamelExampleRequirement.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/utils/ProjectFactory.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/META-INF/MANIFEST.MF
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/test-route-manipulation/pom.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelCatalogDefaultTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorDataFormatTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorLanguageTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CheatSheetsTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DefaultTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DownloadServerTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/JMXNavigatorServerTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/NewFuseProjectWizardTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/PropertiesDropDownChoicesTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/RouteManipulationServerTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/RouteManipulationTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/ServerTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/SingleFuseProjectTest.java

FUSETOOLS-3660: Fix unstable UI tests

---

uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/OpenShiftConfiguration.java
uitests/plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/OpenShiftRequirement.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/DeploymentTest.java
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/FuseOnOpenShiftTest.java

Stabilize uitests after 4.25.0.final release testing

---

uitests/tests/org.jboss.tools.fuse.ui.bot.tests/resources/projects/test-route-manipulation/pom.xml
uitests/tests/org.jboss.tools.fuse.ui.bot.tests/src/org/jboss/tools/fuse/ui/bot/tests/CamelEditorDataFormatTest.java

resolves [FUSETOOLS-3683](https://issues.redhat.com/browse/FUSETOOLS-3683) and [FUSETOOLS-3684](https://issues.redhat.com/browse/FUSETOOLS-3684)

Fix UI tests after jbt-4.27.0.AM1 testing
